sqlplus -s username/xxx@SID <<EOF
DROP TABLE I2B2DEMODATA.Observation_fact_PMS_Notes PURGE;
DROP TABLE "I2B2DEMODATA"."OBSERVATION_FACT_TEMP" PURGE;
DROP TABLE "I2B2METADATA"."I2B2_LEAVES" PURGE;
DROP TABLE "I2B2METADATA"."I2B2_FOLDERS" PURGE;
DROP TABLE "I2B2METADATA"."I2B2_FOLDERS_FULLNAME" PURGE;
DROP TABLE I2B2METADATA.I2B2_TEMP PURGE;
DROP TABLE I2B2DEMODATA.clinical_notes_log PURGE;
DROP TABLE I2B2DEMODATA.concept_counts_temp PURGE;
DROP TABLE I2B2DEMODATA.concept_counts_temp2 PURGE;
DROP TABLE I2B2DEMODATA.polarity_positive PURGE;
DROP TABLE "I2B2DEMODATA"."NODE_METADATA_TEMP" PURGE;
exit;
EOF