/*************************************************/

grant SELECT on "BIOPORTAL_I2B2"."I2B2_NDFRT_FULL" to "TM_LZ" ;

grant SELECT on "BIOPORTAL_I2B2"."I2B2_MSH_FULL" to "TM_LZ" ;

grant SELECT on "BIOPORTAL_I2B2"."I2B2_ICD9CM_FULL" to "TM_LZ" ;


grant SELECT on "BIOPORTAL_I2B2"."I2B2_ICD10CM_FULL" to "TM_LZ" ;


grant SELECT on "BIOPORTAL_I2B2"."I2B2_SNOMED_FULL" to "TM_LZ" ;


grant SELECT on "BIOPORTAL_I2B2"."I2B2_HPO_FULL" to "TM_LZ" ;
/************************************************/
create TABLE TM_LZ."Export_PMS_Clinical_Notes" 
(
  ENCOUNTER_NUM VARCHAR2(1000 BYTE) 
, PATIENT_NUM VARCHAR2(50 BYTE) 
, CONCEPT_CD VARCHAR2(50 BYTE) 
, PROVIDER_ID VARCHAR2(50 BYTE) 
, START_DATE VARCHAR2(50 BYTE) 
, MODIFIER_CD VARCHAR2(100 BYTE) 
, INSTANCE_NUM VARCHAR2(100 BYTE) 
, VALTYPE_CD VARCHAR2(50 BYTE) 
, TVAL_CHAR CLOB 
, NVAL_NUM VARCHAR2(4000 BYTE) 
, VALUEFLAG_CD VARCHAR2(4000 BYTE) 
, QUANTITY_NUM VARCHAR2(4000 BYTE) 
, UNITS_CD VARCHAR2(4000 BYTE) 
, END_DATE VARCHAR2(4000 BYTE) 
, LOCATION_CD VARCHAR2(4000 BYTE) 
, CONFIDENCE_NUM VARCHAR2(4000 BYTE) 
, SOURCESYSTEM_CD VARCHAR2(4000 BYTE) 
, OBSERVATION_BLOB VARCHAR2(4000 BYTE) 
);

CREATE INDEX "TM_LZ"."CONCEPTCD_NOTES" ON "TM_LZ"."Export_PMS_Clinical_Notes" ("CONCEPT_CD");

CREATE TABLE TM_LZ.Observation_fact_PMS_Notes
( "CONCEPT_CODE" VARCHAR2(100 CHAR) NOT NULL ENABLE,
"ENCOUNTER_NUM"  NUMBER(38,0),
"PATIENT_NUM"  NUMBER(38,0),
"CONCEPT_CD" VARCHAR2(50 BYTE),
"PROVIDER_ID" VARCHAR2(50 BYTE),
"START_DATE" VARCHAR2(50 BYTE),
"MODIFIER_CD" VARCHAR2(100 BYTE),
"INSTANCE_NUM" NUMBER(18,0),
"VALTYPE_CD" VARCHAR2(50 BYTE),
"TVAL_CHAR" VARCHAR2(4000 BYTE),
"NVAL_NUM" VARCHAR2(4000 BYTE),
"VALUEFLAG_CD" VARCHAR2(4000 BYTE),
"QUANTITY_NUM" VARCHAR2(4000 BYTE),
"UNITS_CD" VARCHAR2(4000 BYTE),
"END_DATE" VARCHAR2(4000 BYTE),
"LOCATION_CD" VARCHAR2(4000 BYTE),
"CONFIDENCE_NUM" VARCHAR2(4000 BYTE),
"SOURCESYSTEM_CD" VARCHAR2(4000 BYTE),
"OBSERVATION_BLOB" VARCHAR2(4000 BYTE)
);

   create index TM_LZ.conceptcd_obpms on TM_LZ.Observation_fact_PMS_Notes(CONCEPT_CD);

 CREATE TABLE "TM_LZ"."OBSERVATION_FACT_TEMP" 
   (	"ENCOUNTER_NUM" NUMBER(38,0), 
	"PATIENT_NUM" NUMBER(38,0), 
	"CONCEPT_CD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PROVIDER_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"START_DATE" DATE, 
	"MODIFIER_CD" VARCHAR2(100 BYTE), 
	"VALTYPE_CD" VARCHAR2(50 BYTE), 
	"TVAL_CHAR" VARCHAR2(4000 BYTE), 
	"NVAL_NUM" NUMBER(18,5), 
	"VALUEFLAG_CD" VARCHAR2(500 BYTE), 
	"QUANTITY_NUM" NUMBER(18,5), 
	"UNITS_CD" VARCHAR2(500 BYTE), 
	"END_DATE" DATE, 
	"LOCATION_CD" VARCHAR2(100 BYTE), 
	"CONFIDENCE_NUM" NUMBER(18,0), 
	"UPDATE_DATE" DATE, 
	"DOWNLOAD_DATE" DATE, 
	"IMPORT_DATE" DATE, 
	"SOURCESYSTEM_CD" VARCHAR2(50 BYTE), 
	"UPLOAD_ID" NUMBER(38,0), 
	"OBSERVATION_BLOB" CLOB, 
	"INSTANCE_NUM" NUMBER(18,0) DEFAULT 1 NOT NULL ENABLE
   );
   
      create index TM_LZ.conceptcd_obfact on TM_LZ.OBSERVATION_FACT_TEMP(CONCEPT_CD);


    CREATE TABLE "TM_LZ"."I2B2_LEAVES" 
   (	"C_HLEVEL" NUMBER(22,0), 
	"C_FULLNAME" VARCHAR2(700 BYTE) NOT NULL ENABLE, 
	"C_NAME" VARCHAR2(2000 BYTE), 
	"C_SYNONYM_CD" CHAR(1 BYTE), 
	"C_VISUALATTRIBUTES" CHAR(3 BYTE), 
	"C_TOTALNUM" NUMBER(22,0), 
	"C_BASECODE" VARCHAR2(50 BYTE), 
	"C_METADATAXML" CLOB, 
	"C_FACTTABLECOLUMN" VARCHAR2(50 BYTE), 
	"C_TABLENAME" VARCHAR2(50 BYTE), 
	"C_COLUMNNAME" VARCHAR2(50 BYTE), 
	"C_COLUMNDATATYPE" VARCHAR2(50 BYTE), 
	"C_OPERATOR" VARCHAR2(10 BYTE), 
	"C_DIMCODE" VARCHAR2(700 BYTE), 
	"C_COMMENT" CLOB, 
	"C_TOOLTIP" VARCHAR2(1000 BYTE), 
	"UPDATE_DATE" DATE NOT NULL ENABLE, 
	"DOWNLOAD_DATE" DATE, 
	"IMPORT_DATE" DATE, 
	"SOURCESYSTEM_CD" VARCHAR2(50 BYTE), 
	"VALUETYPE_CD" VARCHAR2(50 BYTE), 
	"I2B2_ID" NUMBER(22,0), 
	"M_APPLIED_PATH" VARCHAR2(700 BYTE), 
	"M_EXCLUSION_CD" VARCHAR2(25 BYTE), 
	"C_PATH" VARCHAR2(700 BYTE), 
	"C_SYMBOL" VARCHAR2(50 BYTE)
   );
   
      create index TM_LZ.i2b2_leaves_cfullname on TM_LZ.i2b2_leaves(c_fullname);

   CREATE TABLE "TM_LZ"."I2B2_FOLDERS" 
   (	"C_HLEVEL" NUMBER(22,0), 
	"C_FULLNAME" VARCHAR2(700 BYTE) NOT NULL ENABLE, 
	"C_NAME" VARCHAR2(2000 BYTE), 
	"C_SYNONYM_CD" CHAR(1 BYTE), 
	"C_VISUALATTRIBUTES" CHAR(3 BYTE), 
	"C_TOTALNUM" NUMBER(22,0), 
	"C_BASECODE" VARCHAR2(50 BYTE), 
	"C_METADATAXML" CLOB, 
	"C_FACTTABLECOLUMN" VARCHAR2(50 BYTE), 
	"C_TABLENAME" VARCHAR2(50 BYTE), 
	"C_COLUMNNAME" VARCHAR2(50 BYTE), 
	"C_COLUMNDATATYPE" VARCHAR2(50 BYTE), 
	"C_OPERATOR" VARCHAR2(10 BYTE), 
	"C_DIMCODE" VARCHAR2(700 BYTE), 
	"C_COMMENT" CLOB, 
	"C_TOOLTIP" VARCHAR2(1000 BYTE), 
	"UPDATE_DATE" DATE NOT NULL ENABLE, 
	"DOWNLOAD_DATE" DATE, 
	"IMPORT_DATE" DATE, 
	"SOURCESYSTEM_CD" VARCHAR2(50 BYTE), 
	"VALUETYPE_CD" VARCHAR2(50 BYTE), 
	"I2B2_ID" NUMBER(22,0), 
	"M_APPLIED_PATH" VARCHAR2(700 BYTE), 
	"M_EXCLUSION_CD" VARCHAR2(25 BYTE), 
	"C_PATH" VARCHAR2(700 BYTE), 
	"C_SYMBOL" VARCHAR2(50 BYTE)
   );
   
   create table "TM_LZ"."I2B2_FOLDERS_FULLNAME" (c_fullname varchar2(1000));

create index TM_LZ.i2b2_folders_fullname on TM_LZ.I2B2_FOLDERS(c_fullname);


create index TM_LZ.i2b2_folders_cfullname on "TM_LZ"."I2B2_FOLDERS_FULLNAME"(c_fullname);

 CREATE TABLE TM_LZ.I2B2_TEMP
( "C_HLEVEL" NUMBER(22,0), 
	"C_FULLNAME" VARCHAR2(700 BYTE) NOT NULL ENABLE, 
	"C_NAME" VARCHAR2(2000 BYTE), 
	"C_SYNONYM_CD" CHAR(1 BYTE), 
	"C_VISUALATTRIBUTES" CHAR(3 BYTE), 
	"C_TOTALNUM" NUMBER(22,0), 
	"C_BASECODE" VARCHAR2(50 BYTE), 
	"C_METADATAXML" CLOB, 
	"C_FACTTABLECOLUMN" VARCHAR2(50 BYTE), 
	"C_TABLENAME" VARCHAR2(50 BYTE), 
	"C_COLUMNNAME" VARCHAR2(50 BYTE), 
	"C_COLUMNDATATYPE" VARCHAR2(50 BYTE), 
	"C_OPERATOR" VARCHAR2(10 BYTE), 
	"C_DIMCODE" VARCHAR2(700 BYTE), 
	"C_COMMENT" CLOB, 
	"C_TOOLTIP" VARCHAR2(1000 BYTE), 
	"UPDATE_DATE" DATE NOT NULL ENABLE, 
	"DOWNLOAD_DATE" DATE, 
	"IMPORT_DATE" DATE, 
	"SOURCESYSTEM_CD" VARCHAR2(50 BYTE), 
	"VALUETYPE_CD" VARCHAR2(50 BYTE), 
	"I2B2_ID" NUMBER(22,0), 
	"M_APPLIED_PATH" VARCHAR2(700 BYTE), 
	"M_EXCLUSION_CD" VARCHAR2(25 BYTE), 
	"C_PATH" VARCHAR2(700 BYTE), 
	"C_SYMBOL" VARCHAR2(50 BYTE)
);

create index TM_LZ.cbasecode_temp on TM_LZ.I2B2_TEMP(c_basecode);

grant SELECT on TM_LZ.I2B2_TEMP to "I2B2METADATA" ;

create table TM_LZ.clinical_notes_log
(
step_count varchar2(50 byte),
database_name varchar2(100 byte),
procedure_name varchar2(100 byte),
text varchar2(500 byte),
step_status varchar2(100 byte),
job_date timestamp(6),
time_elapsed_seconds number(18,4)
);


 CREATE TABLE TM_LZ.concept_counts_temp
( "ENCOUNTER_NUM" NUMBER(38,0),
"PATIENT_NUM" NUMBER(38,0),
"C_FULLNAME" VARCHAR2(1000 BYTE) NOT NULL ENABLE
);

CREATE TABLE TM_LZ.concept_counts_temp2
( "C_FULLNAME" VARCHAR2(2000 BYTE),
"ENCOUNTER_NUM" NUMBER(38,0),
"PATIENT_NUM" NUMBER(38,0)
);

 CREATE TABLE TM_LZ.polarity_positive 
   (	"ENCOUNTER_NUM" NUMBER(38,0), 
	"PATIENT_NUM" NUMBER(38,0), 
	"CONCEPT_CD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PROVIDER_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"START_DATE" DATE, 
	"MODIFIER_CD" VARCHAR2(100 BYTE), 
	"VALTYPE_CD" VARCHAR2(50 BYTE), 
	"TVAL_CHAR" VARCHAR2(4000 BYTE), 
	"NVAL_NUM" NUMBER(18,5), 
	"VALUEFLAG_CD" VARCHAR2(500 BYTE), 
	"QUANTITY_NUM" NUMBER(18,5), 
	"UNITS_CD" VARCHAR2(500 BYTE), 
	"END_DATE" DATE, 
	"LOCATION_CD" VARCHAR2(100 BYTE), 
	"CONFIDENCE_NUM" NUMBER(18,0), 
	"UPDATE_DATE" DATE, 
	"DOWNLOAD_DATE" DATE, 
	"IMPORT_DATE" DATE, 
	"SOURCESYSTEM_CD" VARCHAR2(50 BYTE), 
	"UPLOAD_ID" NUMBER(38,0), 
	"OBSERVATION_BLOB" CLOB, 
	"INSTANCE_NUM" NUMBER(18,0) DEFAULT 1 NOT NULL ENABLE
   ); 

   create index TM_LZ.concept_cd_polarity on TM_LZ.polarity_positive (CONCEPT_CD);

  CREATE TABLE "TM_LZ"."NODE_METADATA_TEMP" 
   (	"CONCEPT_PATH" VARCHAR2(700 BYTE) NOT NULL ENABLE, 
	"PARENT_CONCEPT_PATH" VARCHAR2(2800 BYTE), 
	"VALUE" NUMBER, 
	"TYPE" VARCHAR2(50 BYTE), 
	"NODE_METADATA_ID" NUMBER
   );
   
   grant SELECT on "BIOPORTAL_I2B2"."I2B2_HPO_FULL" to "TM_LZ";

grant SELECT ON "BIOPORTAL_I2B2"."I2B2_ICD9CM_FULL" TO "TM_LZ";


grant select,insert on i2b2metadata.i2b2 to tm_lz;

grant select on "UMLS_TOP5_2014AB"."MRCONSO"  to tm_lz;

grant select on i2b2demodata.patient_dimension to tm_lz;

grant select,insert,update,alter on i2b2demodata.observation_fact to tm_lz;

grant select,insert on i2b2demodata.concept_dimension to tm_lz;

grant select,insert,update on I2B2DEMODATA.NODE_METADATA to tm_lz;

grant select on "I2B2DEMODATA"."NODE_METADATA_ID"  to tm_lz;

grant select on "I2B2DEMODATA"."PROVIDER_ID_SEQ" to tm_lz;


alter user TM_LZ quota unlimited on TRANSMART;

alter user tm_lz quota UNLIMITED on I2B2_DATA; 