CREATE TABLE BIOMART_USER.COMPUTE_STATS 
   (	"C_FULLNAME" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"DISTINCT_PATIENTS" NUMBER, 
	"DISTINCT_CONCEPTS" NUMBER, 
	"NUMBER_OF_FACTS" NUMBER
   );
   
 CREATE TABLE "BIOMART_USER"."CONCEPT_STATS" 
   (	"SOURCESYSTEM_CD" VARCHAR2(50 BYTE), 
	"COUNT_OF_CONCEPTS" NUMBER
   );
   
 CREATE TABLE "BIOMART_USER"."OBSERVATION_STATS" 
   (	"DATASOURCE" VARCHAR2(100 BYTE), 
	"NB_OBSERVATION_FACT" NUMBER, 
	"DISTINCT_PATIENT_NUM" NUMBER, 
	"DISTINT_CONCEPT_CD" NUMBER, 
	"MIN_START_DATE" DATE, 
	"MAX_START_DATE" DATE
   );
   
 CREATE TABLE "BIOMART_USER"."SCHEMA_STATS" 
   (	"OWNER" VARCHAR2(30 BYTE), 
	"GB" VARCHAR2(9 BYTE)
   );
 