DROP TABLE "PCORI_CDMV3"."PRO_CM_STAGING";
DROP TABLE "PCORI_CDMV3"."PRO_CM";

CREATE TABLE "PCORI_CDMV3"."PRO_CM_STAGING" 
   (	"PRO_ITEM" VARCHAR2(20 BYTE), 
	"PRO_LOINC" VARCHAR2(20 BYTE), 
	"PRO_RESPONSE" NUMBER(38,0), 
	"PRO_METHOD" VARCHAR2(20 BYTE), 
	"PRO_MODE" VARCHAR2(20 BYTE), 
	"PRO_CAT" VARCHAR2(20 BYTE), 
  "PRO_RECOMMENDATION" VARCHAR2(20 BYTE),
	"RAW_PRO_RESPONSE" VARCHAR2(200 BYTE)
   );

COMMIT;

Insert into PCORI_CDMV3.PRO_CM_STAGING (PRO_ITEM,PRO_LOINC,PRO_RESPONSE,PRO_METHOD,PRO_MODE,PRO_CAT,PRO_RECOMMENDATION, RAW_PRO_RESPONSE) values ('PN_0005','61967-6',5,'EC','PR','N','Adult','The patient has been diagnosed with depression or bipolar/manic depression ');
Insert into PCORI_CDMV3.PRO_CM_STAGING (PRO_ITEM,PRO_LOINC,PRO_RESPONSE,PRO_METHOD,PRO_MODE,PRO_CAT,PRO_RECOMMENDATION, RAW_PRO_RESPONSE) values ('PN_0005','61967-6',1,'EC','PR','N','Adult','The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV3.PRO_CM_STAGING (PRO_ITEM,PRO_LOINC,PRO_RESPONSE,PRO_METHOD,PRO_MODE,PRO_CAT,PRO_RECOMMENDATION, RAW_PRO_RESPONSE) values ('PN_0007','61998-1',1,'EC','PR','N','Adult','The patient never experienced any of these symptoms neither insomnia ');
Insert into PCORI_CDMV3.PRO_CM_STAGING (PRO_ITEM,PRO_LOINC,PRO_RESPONSE,PRO_METHOD,PRO_MODE,PRO_CAT,PRO_RECOMMENDATION, RAW_PRO_RESPONSE) values ('PN_0007','61998-1',5,'EC','PR','N','Adult','The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV3.PRO_CM_STAGING (PRO_ITEM,PRO_LOINC,PRO_RESPONSE,PRO_METHOD,PRO_MODE,PRO_CAT,PRO_RECOMMENDATION, RAW_PRO_RESPONSE) values ('PN_0008','75417-6',3,'EC','PR','N','Adult','The patient''s interest in social interaction increased in adulthood');
Insert into PCORI_CDMV3.PRO_CM_STAGING (PRO_ITEM,PRO_LOINC,PRO_RESPONSE,PRO_METHOD,PRO_MODE,PRO_CAT,PRO_RECOMMENDATION, RAW_PRO_RESPONSE) values ('PN_0008','75417-6',2,'EC','PR','N','Adult','The patient''s interest in social interaction decreased in adulthood');
Insert into PCORI_CDMV3.PRO_CM_STAGING (PRO_ITEM,PRO_LOINC,PRO_RESPONSE,PRO_METHOD,PRO_MODE,PRO_CAT,PRO_RECOMMENDATION, RAW_PRO_RESPONSE) values ('PN_0013','75416-8',4,'EC','PR','N','Pediatric','The patient has been diagnosed with depression or bipolar/manic depression');
Insert into PCORI_CDMV3.PRO_CM_STAGING (PRO_ITEM,PRO_LOINC,PRO_RESPONSE,PRO_METHOD,PRO_MODE,PRO_CAT,PRO_RECOMMENDATION, RAW_PRO_RESPONSE) values ('PN_0018','61949-4',1,'EC','PR','N','Recommended','The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV3.PRO_CM_STAGING (PRO_ITEM,PRO_LOINC,PRO_RESPONSE,PRO_METHOD,PRO_MODE,PRO_CAT,PRO_RECOMMENDATION, RAW_PRO_RESPONSE) values ('PN_0018','61949-4',5,'EC','PR','N','Recommended','The patient has been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder; or the patient repeatedly exhibited anxiety');

COMMIT;
  
CREATE TABLE PCORI_CDMV3.PRO_CM 
(	
  PRO_CM_ID VARCHAR2(200 BYTE), /* New Column */
  PATID VARCHAR2(20 BYTE), 
	ENCOUNTERID VARCHAR2(20 BYTE), 
	PRO_ITEM VARCHAR2(20 BYTE), 
	PRO_LOINC VARCHAR2(20 BYTE), 
	PRO_DATE VARCHAR2(20 BYTE), 
	PRO_TIME VARCHAR2(20 BYTE), 
	PRO_RESPONSE NUMBER(38,0), 
	PRO_METHOD VARCHAR2(20 BYTE), 
	PRO_MODE VARCHAR2(20 BYTE), 
	PRO_CAT VARCHAR2(20 BYTE), 
	RAW_PRO_CODE VARCHAR2(20 BYTE), 
	RAW_PRO_RESPONSE VARCHAR2(200 BYTE)
);

COMMIT;

-- ADULT DEPRESSION PN-0005

INSERT INTO PCORI_CDMV3.PRO_CM (
PRO_CM_ID, PATID,
PRO_ITEM, PRO_LOINC,
PRO_DATE, PRO_METHOD, 
PRO_MODE, PRO_CAT,
RAW_PRO_RESPONSE
)
SELECT
OBF.PATIENT_NUM || '_' || CD.CONCEPT_CD, OBF.PATIENT_NUM, 
PRS.PRO_ITEM, PRS.PRO_LOINC, 
OBF.IMPORT_DATE, PRS.PRO_METHOD, 
PRS.PRO_MODE, PRS.PRO_CAT,
OBF.TVAL_CHAR
FROM 
(I2B2DEMODATA.OBSERVATION_FACT) OBF, (I2B2DEMODATA.CONCEPT_DIMENSION) CD, 
(I2B2METADATA.I2B2) I2, (PCORI_CDMV3.PRO_CM_STAGING) PRS
WHERE 
OBF.CONCEPT_CD = CD.CONCEPT_CD
AND
CD.CONCEPT_CD = I2.C_BASECODE 
AND 
I2.C_FULLNAME LIKE '%In the past 7 days I felt depressed%'
AND 
I2.SOURCESYSTEM_CD IN ('HMS_PMS_REG_C00', 'HMS_PMS_REG_C01', 'HMS_PMS_REG_PRO')
AND 
PRS.RAW_PRO_RESPONSE LIKE '%diagnosed with depression%'
AND 
PRS.PRO_RECOMMENDATION = 'Adult';

COMMIT;
-- Adult Insomnia PN-0007

INSERT INTO PCORI_CDMV3.PRO_CM (
PRO_CM_ID, PATID,
PRO_ITEM, PRO_LOINC,
PRO_DATE, PRO_METHOD, 
PRO_MODE, PRO_CAT,
RAW_PRO_RESPONSE
)
SELECT
OBF.PATIENT_NUM || '_' || CD.CONCEPT_CD, OBF.PATIENT_NUM, 
PRS.PRO_ITEM, PRS.PRO_LOINC, 
OBF.IMPORT_DATE, PRS.PRO_METHOD, 
PRS.PRO_MODE, PRS.PRO_CAT,
OBF.TVAL_CHAR
FROM 
(I2B2DEMODATA.OBSERVATION_FACT) OBF, (I2B2DEMODATA.CONCEPT_DIMENSION) CD, 
(I2B2METADATA.I2B2) I2, (PCORI_CDMV3.PRO_CM_STAGING) PRS
WHERE 
OBF.CONCEPT_CD = CD.CONCEPT_CD
AND
CD.CONCEPT_CD = I2.C_BASECODE 
AND 
I2.C_FULLNAME LIKE '%In the past 7 days I had a problem with my sleep%'
AND 
I2.SOURCESYSTEM_CD IN ('HMS_PMS_REG_C00', 'HMS_PMS_REG_C01', 'HMS_PMS_REG_PRO')
AND 
PRS.RAW_PRO_RESPONSE LIKE '%insomnia%'
AND 
PRS.PRO_RECOMMENDATION = 'Adult';

COMMIT;
-- Adult Social Roles PN-0008

INSERT INTO PCORI_CDMV3.PRO_CM (
PRO_CM_ID, PATID,
PRO_ITEM, PRO_LOINC,
PRO_DATE, PRO_METHOD, 
PRO_MODE, PRO_CAT,
RAW_PRO_RESPONSE
)
SELECT
OBF.PATIENT_NUM || '_' || CD.CONCEPT_CD, OBF.PATIENT_NUM, 
PRS.PRO_ITEM, PRS.PRO_LOINC, 
OBF.IMPORT_DATE, PRS.PRO_METHOD, 
PRS.PRO_MODE, PRS.PRO_CAT,
OBF.TVAL_CHAR
FROM 
(I2B2DEMODATA.OBSERVATION_FACT) OBF, (I2B2DEMODATA.CONCEPT_DIMENSION) CD, 
(I2B2METADATA.I2B2) I2, (PCORI_CDMV3.PRO_CM_STAGING) PRS
WHERE 
OBF.CONCEPT_CD = CD.CONCEPT_CD
AND
CD.CONCEPT_CD = I2.C_BASECODE 
AND 
I2.C_FULLNAME LIKE '%I have trouble doing all of my regular leisure activities with others%'
AND 
I2.SOURCESYSTEM_CD IN ('HMS_PMS_REG_C00', 'HMS_PMS_REG_C01', 'HMS_PMS_REG_PRO')
AND 
PRS.RAW_PRO_RESPONSE LIKE '%interest in social interaction%'
AND 
PRS.PRO_RECOMMENDATION = 'Adult';

COMMIT;
-- PEDIATRIC DEPRESSION PN-0013

INSERT INTO PCORI_CDMV3.PRO_CM (
PRO_CM_ID, PATID,
PRO_ITEM, PRO_LOINC,
PRO_DATE, PRO_METHOD, 
PRO_MODE, PRO_CAT,
RAW_PRO_RESPONSE
)
SELECT
OBF.PATIENT_NUM || '_' || CD.CONCEPT_CD, OBF.PATIENT_NUM, 
PRS.PRO_ITEM, PRS.PRO_LOINC, 
OBF.IMPORT_DATE, PRS.PRO_METHOD, 
PRS.PRO_MODE, PRS.PRO_CAT,
OBF.TVAL_CHAR
FROM 
(I2B2DEMODATA.OBSERVATION_FACT) OBF, (I2B2DEMODATA.CONCEPT_DIMENSION) CD, 
(I2B2METADATA.I2B2) I2, (PCORI_CDMV3.PRO_CM_STAGING) PRS
WHERE 
OBF.CONCEPT_CD = CD.CONCEPT_CD
AND
CD.CONCEPT_CD = I2.C_BASECODE 
AND 
I2.C_FULLNAME LIKE '%How often do you feel really sad%'
AND 
I2.SOURCESYSTEM_CD IN ('HMS_PMS_REG_C00', 'HMS_PMS_REG_C01', 'HMS_PMS_REG_PRO')
AND 
PRS.RAW_PRO_RESPONSE LIKE '%diagnosed with depression%'
AND 
PRS.PRO_RECOMMENDATION = 'Pediatric';

COMMIT;
-- RECOMMENDED ANXIETY FOR PEDIATRICS AND ADULTS PN-0018

INSERT INTO PCORI_CDMV3.PRO_CM (
PRO_CM_ID, PATID,
PRO_ITEM, PRO_LOINC,
PRO_DATE, PRO_METHOD, 
PRO_MODE, PRO_CAT,
RAW_PRO_RESPONSE
)
SELECT
OBF.PATIENT_NUM || '_' || CD.CONCEPT_CD, OBF.PATIENT_NUM, 
PRS.PRO_ITEM, PRS.PRO_LOINC, 
OBF.IMPORT_DATE, PRS.PRO_METHOD, 
PRS.PRO_MODE, PRS.PRO_CAT,
OBF.TVAL_CHAR
FROM 
(I2B2DEMODATA.OBSERVATION_FACT) OBF, (I2B2DEMODATA.CONCEPT_DIMENSION) CD, 
(I2B2METADATA.I2B2) I2, (PCORI_CDMV3.PRO_CM_STAGING) PRS
WHERE 
OBF.CONCEPT_CD = CD.CONCEPT_CD
AND
CD.CONCEPT_CD = I2.C_BASECODE 
AND 
I2.C_FULLNAME LIKE '%In the past 7 days I felt uneasy%'
AND 
I2.SOURCESYSTEM_CD IN ('HMS_PMS_REG_C00', 'HMS_PMS_REG_C01', 'HMS_PMS_REG_PRO')
AND 
PRS.RAW_PRO_RESPONSE LIKE '%anxiety disorder%'
AND 
PRS.PRO_RECOMMENDATION = 'Recommended';

COMMIT;
-- ALL UPDATES

UPDATE PCORI_CDMV3.PRO_CM SET PRO_RESPONSE = 5 
WHERE RAW_PRO_RESPONSE = 'Very much';

UPDATE PCORI_CDMV3.PRO_CM SET PRO_RESPONSE = 5 
WHERE RAW_PRO_RESPONSE = 'Always';

UPDATE PCORI_CDMV3.PRO_CM SET PRO_RESPONSE = 4 
WHERE RAW_PRO_RESPONSE = 'Quite a bit';

UPDATE PCORI_CDMV3.PRO_CM SET PRO_RESPONSE = 4 
WHERE RAW_PRO_RESPONSE = 'Usually';

UPDATE PCORI_CDMV3.PRO_CM SET PRO_RESPONSE = 3 
WHERE RAW_PRO_RESPONSE = 'Somewhat';

UPDATE PCORI_CDMV3.PRO_CM SET PRO_RESPONSE = 3 
WHERE RAW_PRO_RESPONSE = 'Sometimes';

UPDATE PCORI_CDMV3.PRO_CM SET PRO_RESPONSE = 2 
WHERE RAW_PRO_RESPONSE = 'A little bit';

UPDATE PCORI_CDMV3.PRO_CM SET PRO_RESPONSE = 1 
WHERE RAW_PRO_RESPONSE = 'Not at all';

UPDATE PCORI_CDMV3.PRO_CM SET PRO_RESPONSE = 1 
WHERE RAW_PRO_RESPONSE = 'Never';

COMMIT;