--------------------------------------------------------
--  File created - Wednesday-December-10-2014   
--------------------------------------------------------

Insert into I2B2DEMODATA.QT_QUERY_STATUS_TYPE (STATUS_TYPE_ID,NAME,DESCRIPTION) values (1,'QUEUED',' WAITING IN QUEUE TO START PROCESS');
Insert into I2B2DEMODATA.QT_QUERY_STATUS_TYPE (STATUS_TYPE_ID,NAME,DESCRIPTION) values (2,'PROCESSING','PROCESSING');
Insert into I2B2DEMODATA.QT_QUERY_STATUS_TYPE (STATUS_TYPE_ID,NAME,DESCRIPTION) values (3,'FINISHED','FINISHED');
Insert into I2B2DEMODATA.QT_QUERY_STATUS_TYPE (STATUS_TYPE_ID,NAME,DESCRIPTION) values (4,'ERROR','ERROR');
Insert into I2B2DEMODATA.QT_QUERY_STATUS_TYPE (STATUS_TYPE_ID,NAME,DESCRIPTION) values (5,'INCOMPLETE','INCOMPLETE');
Insert into I2B2DEMODATA.QT_QUERY_STATUS_TYPE (STATUS_TYPE_ID,NAME,DESCRIPTION) values (6,'COMPLETED','COMPLETED');
Insert into I2B2DEMODATA.QT_QUERY_STATUS_TYPE (STATUS_TYPE_ID,NAME,DESCRIPTION) values (7,'MEDIUM_QUEUE','MEDIUM QUEUE');
Insert into I2B2DEMODATA.QT_QUERY_STATUS_TYPE (STATUS_TYPE_ID,NAME,DESCRIPTION) values (8,'LARGE_QUEUE','LARGE QUEUE');
Insert into I2B2DEMODATA.QT_QUERY_STATUS_TYPE (STATUS_TYPE_ID,NAME,DESCRIPTION) values (9,'CANCELLED','CANCELLED');
Insert into I2B2DEMODATA.QT_QUERY_STATUS_TYPE (STATUS_TYPE_ID,NAME,DESCRIPTION) values (10,'TIMEDOUT','TIMEDOUT');
