insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('PubMed','http://www.ncbi.nlm.nih.gov/pubmed/?term=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('EMBASE','http://www.elsevier.com/s/search.html?profile=_default&form=sitesearch&collection=elsevier-meta&query=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('COCHRANE','http://onlinelibrary.wiley.com/cochranelibrary/search?searchRow.searchCriteria.term=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('Wikipedia','https://en.wikipedia.org/wiki/',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('NORD''s','https://www.rarediseases.org/rare-disease-information/rare-diseases/viewSearchResults?term=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('GeneCards','http://www.genecards.org/cgi-bin/carddisp.pl?gene=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('OMIM','http://omim.org/search?index=entry&start=1&limit=10&search=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('Ensembl project','http://grch37.ensembl.org/Human/Search/Results?q=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('GTEx project','http://www.gtexportal.org/home/gene/',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('WikiGenes','http://www.wikigenes.org/?search=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('GTR','http://www.ncbi.nlm.nih.gov/gtr/genes/?term=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('ClinVar','http://www.ncbi.nlm.nih.gov/clinvar?term=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('GeneTests','https://www.genetests.org/search/disorders.php?search=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('ClinicalTrials.gov','https://clinicaltrials.gov/ct2/results?term=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('Food & Drug Administration','http://google2.fda.gov/search?q=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('European Medicines Agency','http://www.ema.europa.eu/ema/index.jsp?curl=pages%2Fincludes%2Fmedicines%2Fmedicines_landing_page.jsp&searchkwByEnter=true&quickSearch=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('UCSC','http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&position=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('WHO','http://search.who.int/search?q=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('ExAC-Gene','http://exac.broadinstitute.org/gene/',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('ExAC-Transcript','http://exac.broadinstitute.org/transcript/',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('ExAC-Variant','http://exac.broadinstitute.org/variant/',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('ExAC Multi-allelic Variant','http://exac.broadinstitute.org/dbsnp/',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('ExAC-Region','http://exac.broadinstitute.org/region/',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('EMBASE','http://www.elsevier.com/s/search.html?profile=_default&form=sitesearch&collection=elsevier-meta&query=',BIOMART.web_id.NEXTVAL);
insert into BIOMART.WEB_LINKS (NAME,URL,ID) values('NCBI','http://www.ncbi.nlm.nih.gov/gquery/?term=',BIOMART.web_id.NEXTVAL);

