/usr/bin/time -v sqlplus -s biomart_user/dwtst@BCH_DWTST<<EOF

CREATE TABLE TRIMMED_CONCEPTS AS
SELECT DISTINCT C_BASECODE
FROM TM_LZ.NLP_EMERGE
INNER JOIN "TM_LZ"."I2B2_SNOMED" ON CONCEPT_CD = 'SNO:' || C_BASECODE
WHERE CONCEPT_POLARITY=1;

exit;
EOF
