/usr/bin/time -v sqlplus -s biomart_user/dwtst@BCH_DWTST<<EOF

CREATE INDEX "NLP_CONCEPT" ON "TM_LZ"."NLP_EMERGE" ("CONCEPT_CD", "CONCEPT_POLARITY") PARALLEL 4 NOLOGGING;

CREATE INDEX "I2B2_SNOMED" ON "TM_LZ"."I2B2_SNOMED" ("C_BASECODE") PARALLEL 4 NOLOGGING;
exit;
EOF
