OPTIONS (DIRECT=TRUE, SKIP=0) UNRECOVERABLE
load data
infile 'emerge_asd_15k.txt.pre_pms_dn.out.snowmed.positive.obsf'
APPEND into table TM_WZ.OBSF3 
fields terminated by "," OPTIONALLY ENCLOSED BY '"'  TRAILING NULLCOLS
("ENCOUNTER_NUM","PATIENT_NUM","CONCEPT_CD","PROVIDER_ID","START_DATE","MODIFIER_CD","VALTYPE_CD","TVAL_CHAR","NVAL_NUM","VALUEFLAG_CD","QUANTITY_NUM","UNITS_CD","END_DATE","LOCATION_CD","CONFIDENCE_NUM","UPDATE_DATE","DOWNLOAD_DATE","IMPORT_DATE","SOURCESYSTEM_CD","UPLOAD_ID","OBSERVATION_BLOB","INSTANCE_NUM")
