OPTIONS (DIRECT=TRUE, SKIP=1) UNRECOVERABLE
load data
infile 'emerge_asd_15k.txt.pre_pms_dn.out.snowmed' "STR ''"
APPEND into table NLP_EMERGE 
fields terminated by "|" OPTIONALLY ENCLOSED BY '"'  TRAILING NULLCOLS
("RECORD_ID","ENCOUNTER_NUM","PATIENT_NUM","CONCEPT_CD","PROVIDER_ID","START_DATE","INSTANCE_NUM","CONCEPT_POLARITY","SRC_INSTANCE_NUM","DOC_ID")
