OPTIONS (DIRECT=TRUE, SKIP=1) UNRECOVERABLE
load data
infile 'SNOMED_2014AA_short_i2b2.txt' "STR ''"
APPEND into table I2B2_SNOMED 
fields terminated by "|" OPTIONALLY ENCLOSED BY '"'  TRAILING NULLCOLS
("C_HLEVEL" char(2000),"C_FULLNAME","C_NAME","C_SYNONYM_CD","C_VISUALATTRIBUTES","C_BASECODE","C_FACTTABLECOLUMN","C_TABLENAME","C_COLUMNNAME","C_COLUMNDATATYPE","C_OPERATOR","C_DIMCODE","C_TOOLTIP" char(4000),"SOURCESYSTEM_CD","C_SYMBOL","C_PATH","I_SNOMED_CT","I_SNOMED_RT","I_CUI","I_TUI","I_CTV3","I_FULL_ID","UPDATE_DATE","PARENT_FULLIDS","M_APPLIED_PATH")
