create or replace PROCEDURE PATIENT_COUNT_FOR_CONCEPT (MY_CONCEPT_CD IN VARCHAR2) AS 

cnt INTEGER;

BEGIN

select count(distinct(PATIENT_NUM)) into cnt from I2B2DEMODATA.OBSERVATION_FACT
where CONCEPT_CD=MY_CONCEPT_CD
and MODIFIER_CD='CUSTOM:OBSERVATION_VALID:' 
and TVAL_CHAR='1';

MERGE INTO I2B2DEMODATA.NODE_METADATA nm
USING (
  SELECT CONCEPT_PATH, SUBSTR(CONCEPT_PATH,0,INSTR(CONCEPT_PATH,'\',-2)) PARENT_CONCEPT_PATH, 'PATIENT_COUNT' TYPE from CONCEPT_DIMENSION where CONCEPT_CD=MY_CONCEPT_CD
) u
ON (u.CONCEPT_PATH = nm.CONCEPT_PATH and u.PARENT_CONCEPT_PATH = nm.PARENT_CONCEPT_PATH and u.TYPE = nm.TYPE)
WHEN MATCHED THEN 
UPDATE SET nm.VALUE = cnt
WHEN NOT MATCHED THEN 
INSERT (CONCEPT_PATH, PARENT_CONCEPT_PATH, VALUE, TYPE) VALUES (u.CONCEPT_PATH, u.PARENT_CONCEPT_PATH, u.TYPE, cnt);

commit;

END;


