create or replace PROCEDURE PATIENT_VALID_FOR_CONCEPT (MY_CONCEPT_CD IN VARCHAR2) AS 

cnt INTEGER;
valid VARCHAR2(2);

BEGIN

FOR x IN (
  select distinct(PATIENT_NUM) from I2B2DEMODATA.OBSERVATION_FACT where CONCEPT_CD=MY_CONCEPT_CD and MODIFIER_CD='CUSTOM:OBSERVATION_VALID:' 
)

LOOP

select count(*) into cnt from I2B2DEMODATA.OBSERVATION_FACT where PATIENT_NUM=x.PATIENT_NUM and CONCEPT_CD=MY_CONCEPT_CD and MODIFIER_CD='CUSTOM:OBSERVATION_VALID:' and TVAL_CHAR='1';

if cnt > 0 then
valid := '1';
ELSE
valid := '-1';
END IF;

MERGE INTO I2B2DEMODATA.OBSERVATION_FACT obsf
USING (
  SELECT x.PATIENT_NUM PATIENT_NUM, MY_CONCEPT_CD CONCEPT_CD, 'CUSTOM:PATIENT_VALID:' MODIFIER_CD from dual
) u
ON (u.PATIENT_NUM = obsf.PATIENT_NUM and u.CONCEPT_CD = obsf.CONCEPT_CD and u.MODIFIER_CD = obsf.MODIFIER_CD)
WHEN MATCHED THEN 
UPDATE SET obsf.TVAL_CHAR = valid
WHEN NOT MATCHED THEN 
INSERT (PROVIDER_ID, PATIENT_NUM, CONCEPT_CD, INSTANCE_NUM, MODIFIER_CD, VALTYPE_CD, TVAL_CHAR) VALUES (0, x.PATIENT_NUM, MY_CONCEPT_CD, 1, 'CUSTOM:PATIENT_VALID:', 'T', valid);

commit;

END LOOP;

END;