/usr/bin/time -v sqlplus -s biomart_user/dwtst@BCH_DWTST<<EOF

ALTER INDEX i2b2metadata.I2B2_INDEX2_PART REBUILD;
ALTER INDEX i2b2metadata.I2B2_INDEX3_PART REBUILD;
ALTER INDEX i2b2metadata.I2B2_INDEX4_PART REBUILD;
ALTER INDEX i2b2metadata.I2B2_C_HLEVEL_BASECODE_PART REBUILD;

DROP INDEX "I2B2METADATA"."I2B2_INDEX1_PART";


  CREATE INDEX "I2B2METADATA"."I2B2_INDEX1_PART" ON "I2B2METADATA"."I2B2" ("C_FULLNAME", "C_HLEVEL", "C_SYNONYM_CD", "C_VISUALATTRIBUTES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TRANSMART"  LOCAL
 (PARTITION "P_1" 
PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TRANSMART" 
 ( SUBPARTITION "P4" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P5" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P6" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P7" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P8" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P9" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P10" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P11" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P12" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P13" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P14" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P15" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P16" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P17" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P18" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P19" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P20" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P21" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P22" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P23" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P24" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P25" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P26" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P50" 
  TABLESPACE "TRANSMART" ) , 
 PARTITION "MODIFIERS" 
PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TRANSMART" 
 ( SUBPARTITION "P51" 
  TABLESPACE "TRANSMART" ) ) ;

DROP INDEX "I2B2METADATA"."META_APPLIED_PATH_I2B2_PART";

CREATE INDEX "I2B2METADATA"."META_APPLIED_PATH_I2B2_PART" ON "I2B2METADATA"."I2B2" ("C_HLEVEL", "M_APPLIED_PATH", "M_EXCLUSION_CD", "C_FULLNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TRANSMART"  LOCAL
 (PARTITION "P_1" 
PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TRANSMART" 
 ( SUBPARTITION "P4" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P5" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P6" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P7" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P8" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P9" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P10" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P11" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P12" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P13" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P14" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P15" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P16" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P17" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P18" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P19" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P20" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P21" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P22" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P23" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P24" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P25" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P26" 
  TABLESPACE "TRANSMART" , 
  SUBPARTITION "P50" 
  TABLESPACE "TRANSMART" ) , 
 PARTITION "MODIFIERS" 
PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TRANSMART" 
 ( SUBPARTITION "P51" 
  TABLESPACE "TRANSMART" ) ) ;

exit;
EOF
