source(paste0(r_scripts_path,'getConfig.R'))
source(paste0(r_scripts_path,'toLog.R'))
source(paste0(r_scripts_path,'JDBCConnect.R'))
source(paste0(r_scripts_path,'SendQueries.R'))

conf <- getConfig('config_file')

query_list <- 
  c("ALTER INDEX I2B2DEMODATA.CONCEPTS_FOLDERS_PATS_IDX1 REBUILD",
  "CREATE INDEX I2B2METADATA.i2b2_fullname_text ON i2b2metadata.i2b2(c_fullname) INDEXTYPE IS CTXSYS.CONTEXT",
  "CREATE INDEX cd_concept_path_text ON i2b2demodata.concept_dimension(concept_path) INDEXTYPE IS CTXSYS.CONTEXT",
  paste('CREATE UNIQUE INDEX "I2B2DEMODATA"."OB_FACT_PK" ON "I2B2DEMODATA"."OBSERVATION_FACT" ("ENCOUNTER_NUM", "PATIENT_NUM", "CONCEPT_CD", "PROVIDER_ID", "START_DATE", "MODIFIER_CD")', 
        'PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING',
        'STORAGE(INITIAL 27262976 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645',
        'PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)',
        'TABLESPACE "I2B2_DATA"'),
  paste('CREATE INDEX "I2B2METADATA"."I2B2_INDEX1" ON "I2B2METADATA"."I2B2" ("C_FULLNAME", "C_HLEVEL", "C_SYNONYM_CD", "C_VISUALATTRIBUTES") ',
        'PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS ',
        'STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645',
        'PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)',
        'TABLESPACE "TRANSMART"'),
  "CALL I2B2DEMODATA.STATS_I2B2DEMODATA()",
  "CALL I2B2METADATA.STATS_I2B2METADATA()")
  
  
SendQueries(con,query_list)