
alter session set current_schema=I2B2DEMODATA;

/***
*
* Create modifiers in MODIFIER_DIMENSION_TABLE: CUSTOM:OBSERVATION_VALID, CUSTOM:OBSERVATION_INVALID_REASON, PATIENT_VALID, CONCEPT_VALIDATED */
*
***/

INSERT INTO MODIFIER_DIMENSION (MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, SOURCESYSTEM_CD) 
select '\OBSERVATION_VALID\', 'CUSTOM:OBSERVATION_VALID:', 'OBSERVATION_VALID', 'CTAKES_16TESTFILES' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM MODIFIER_DIMENSION WHERE MODIFIER_CD='CUSTOM:OBSERVATION_VALID:');

INSERT INTO MODIFIER_DIMENSION (MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, SOURCESYSTEM_CD)  
select '\OBSERVATION_INVALID_REASON\', 'CUSTOM:OBSERVATION_INVALID_REASON:', 'OBSERVATION_INVALID_REASON', 'CTAKES_16TESTFILES' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM MODIFIER_DIMENSION WHERE MODIFIER_CD='CUSTOM:OBSERVATION_INVALID_REASON:');

INSERT INTO MODIFIER_DIMENSION (MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, SOURCESYSTEM_CD)  
select '\PATIENT_VALID\', 'CUSTOM:PATIENT_VALID:', 'PATIENT_VALID', 'CTAKES_16TESTFILES' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM MODIFIER_DIMENSION WHERE MODIFIER_CD='CUSTOM:PATIENT_VALID:');

INSERT INTO MODIFIER_DIMENSION (MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, SOURCESYSTEM_CD)  
select '\CONCEPT_VALIDATED\', 'CUSTOM:CONCEPT_VALIDATED:', 'CONCEPT_VALIDATED', 'CTAKES_16TESTFILES' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM MODIFIER_DIMENSION WHERE MODIFIER_CD='CUSTOM:CONCEPT_VALIDATED:');

INSERT INTO MODIFIER_DIMENSION (MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, SOURCESYSTEM_CD)  
select '\HIGHLIGHT\', 'CUSTOM:HIGHLIGHT:', 'HIGHLIGHT', 'CTAKES_16TESTFILES' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM MODIFIER_DIMENSION WHERE MODIFIER_CD='CUSTOM:HIGHLIGHT:');

/**
*
* Add modifiers to i2b2 table
*
*/

INSERT INTO I2B2METADATA.I2B2 (C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_BASECODE,
C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR,
C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, I2B2_ID,
M_APPLIED_PATH, M_EXCLUSION_CD, C_PATH, C_SYMBOL) 
select 2,'\cTAKES Modifiers\OBSERVATION_VALID\', 'OBSERVATION_VALID', 'N', 'RA', 'CUSTOM:OBSERVATION_VALID:', '"<ValueMetadata> 
    <Version>3.02</Version> 
     <TestID>CUSTOM:OBSERVATION_VALID:</TestID> 
     <TestName>OBSERVATION_VALID List</TestName> 
     <DataType>Enum</DataType> 
     <Oktousevalues>Y</Oktousevalues> 
     <EnumValues> 
          <Val description="Positive">1</Val> 
          <Val description="Negative">-1</Val>                             
     </EnumValues> 
</ValueMetadata>"',	'MODIFIER_CD', 'MODIFIER_DIMENSION', 'MODIFIER_PATH',	'T', 'LIKE',
'\OBSERVATION_VALID\', null, '\cTAKES Modifiers\OBSERVATION_VALID\', '04-DEC-2014', 'cTAKES_MODIFIERS', null, '20000',
'\PMS_DN\02 PMS Clinical Notes (cTAKES NLP)\01 SNOMED\%', null, '\cTAKES Modifiers\', 'OBSERVATION_VALID' from DUAL
WHERE NOT EXISTS (SELECT * FROM I2B2METADATA.I2B2 WHERE C_FULLNAME='\cTAKES Modifiers\OBSERVATION_VALID\');

INSERT INTO I2B2METADATA.I2B2 (C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_BASECODE,
C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR,
C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, I2B2_ID,
M_APPLIED_PATH, M_EXCLUSION_CD, C_PATH, C_SYMBOL) 
select 2,'\cTAKES Modifiers\OBSERVATION_INVALID_REASON\',	'OBSERVATION_INVALID_REASON', 'N', 'RA', 'CUSTOM:OBSERVATION_INVALID_REASON:',
null, 'MODIFIER_CD', 'MODIFIER_DIMENSION', 'MODIFIER_PATH',	'T', 'LIKE',
'\OBSERVATION_INVALID_REASON\', null, '\cTAKES Modifiers\OBSERVATION_INVALID_REASON\', '04-DEC-2014', 'cTAKES_MODIFIERS', null, '20000',
'\PMS_DN\02 PMS Clinical Notes (cTAKES NLP)\01 SNOMED\%', null, '\cTAKES Modifiers\', 'OBSERVATION_INVALID_REASON' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM I2B2METADATA.I2B2 WHERE C_FULLNAME='\cTAKES Modifiers\OBSERVATION_INVALID_REASON\');

INSERT INTO I2B2METADATA.I2B2 (C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_BASECODE,
C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR,
C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, I2B2_ID,
M_APPLIED_PATH, M_EXCLUSION_CD, C_PATH, C_SYMBOL) 
select 2,'\cTAKES Modifiers\PATIENT_VALID\',	'PATIENT_VALID', 'N', 'RA', 'CUSTOM:PATIENT_VALID:',
null, 'MODIFIER_CD', 'MODIFIER_DIMENSION', 'MODIFIER_PATH',	'T', 'LIKE',
'\PATIENT_VALID\', null, '\cTAKES Modifiers\PATIENT_VALID\', '04-DEC-2014', 'cTAKES_MODIFIERS', null, '20000',
'\PMS_DN\02 PMS Clinical Notes (cTAKES NLP)\01 SNOMED\%', null, '\cTAKES Modifiers\', 'PATIENT_VALID' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM I2B2METADATA.I2B2 WHERE C_FULLNAME='\cTAKES Modifiers\PATIENT_VALID\');

INSERT INTO I2B2METADATA.I2B2 (C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_BASECODE,
C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR,
C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, I2B2_ID,
M_APPLIED_PATH, M_EXCLUSION_CD, C_PATH, C_SYMBOL) 
select 2,'\cTAKES Modifiers\CONCEPT_VALIDATED\',	'CONCEPT_VALIDATED', 'N', 'RA', 'CUSTOM:CONCEPT_VALIDATED:',
null, 'MODIFIER_CD', 'MODIFIER_DIMENSION', 'MODIFIER_PATH',	'T', 'LIKE',
'\CONCEPT_VALIDATED\', null, '\cTAKES Modifiers\CONCEPT_VALIDATED\', '04-DEC-2014', 'cTAKES_MODIFIERS', null, '20000',
'\PMS_DN\02 PMS Clinical Notes (cTAKES NLP)\01 SNOMED\%', null, '\cTAKES Modifiers\', 'CONCEPT_VALIDATED' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM I2B2METADATA.I2B2 WHERE C_FULLNAME='\cTAKES Modifiers\CONCEPT_VALIDATED\');

INSERT INTO I2B2METADATA.I2B2 (C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_BASECODE,
C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR,
C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, I2B2_ID,
M_APPLIED_PATH, M_EXCLUSION_CD, C_PATH, C_SYMBOL) 
select 2,'\cTAKES Modifiers\HIGHLIGHT\',	'HIGHLIGHT', 'N', 'RA', 'CUSTOM:HIGHLIGHT:',
null, 'MODIFIER_CD', 'MODIFIER_DIMENSION', 'MODIFIER_PATH',	'T', 'LIKE',
'\HIGHLIGHT\', null, '\cTAKES Modifiers\HIGHLIGHT\', '04-DEC-2014', 'cTAKES_MODIFIERS', null, '20000',
'\PMS_DN\02 PMS Clinical Notes (cTAKES NLP)\01 SNOMED\%', null, '\cTAKES Modifiers\', 'HIGHLIGHT' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM I2B2METADATA.I2B2 WHERE C_FULLNAME='\cTAKES Modifiers\HIGHLIGHT\');

/***
*
* Default initial setting for modifiers
*
***/

/* Default initial setting for CUSTOM:OBSERVATION_VALID modifier based on negative polarity  */
insert into OBSERVATION_FACT
(MODIFIER_CD,VALTYPE_CD, TVAL_CHAR,CONCEPT_CD,PATIENT_NUM,ENCOUNTER_NUM,INSTANCE_NUM,OBSERVATION_BLOB,SOURCESYSTEM_CD,PROVIDER_ID)
SELECT 'CUSTOM:OBSERVATION_VALID:','T','1',CONCEPT_CD,PATIENT_NUM,ENCOUNTER_NUM,INSTANCE_NUM,OBSERVATION_BLOB,SOURCESYSTEM_CD,PROVIDER_ID FROM OBSERVATION_FACT O1 WHERE MODIFIER_CD='CUSTOM:POLARITY:' and tval_char='1' 
and NOT EXISTS (SELECT * FROM OBSERVATION_FACT O2 where O1.ENCOUNTER_NUM=O2.ENCOUNTER_NUM AND O1.PATIENT_NUM=O2.PATIENT_NUM AND O1.CONCEPT_CD=O2.CONCEPT_CD AND O1.PROVIDER_ID=O2.PROVIDER_ID AND O2.MODIFIER_CD='CUSTOM:OBSERVATION_VALID:' AND O2.VALTYPE_CD='T' AND O2.TVAL_CHAR='1' AND O1.INSTANCE_NUM=O2.INSTANCE_NUM);

insert into OBSERVATION_FACT
(MODIFIER_CD,VALTYPE_CD, TVAL_CHAR,CONCEPT_CD,PATIENT_NUM,ENCOUNTER_NUM,INSTANCE_NUM,OBSERVATION_BLOB,SOURCESYSTEM_CD,PROVIDER_ID)
SELECT 'CUSTOM:OBSERVATION_VALID:','T','-1',CONCEPT_CD,PATIENT_NUM,ENCOUNTER_NUM,INSTANCE_NUM,OBSERVATION_BLOB,SOURCESYSTEM_CD,PROVIDER_ID FROM OBSERVATION_FACT O1 WHERE MODIFIER_CD='CUSTOM:POLARITY:' and tval_char='-1' 
and NOT EXISTS (SELECT * FROM OBSERVATION_FACT O2 where O1.ENCOUNTER_NUM=O2.ENCOUNTER_NUM AND O1.PATIENT_NUM=O2.PATIENT_NUM AND O1.CONCEPT_CD=O2.CONCEPT_CD AND O1.PROVIDER_ID=O2.PROVIDER_ID AND O2.MODIFIER_CD='CUSTOM:OBSERVATION_VALID:' AND O2.VALTYPE_CD='T' AND O2.TVAL_CHAR='-1' AND O1.INSTANCE_NUM=O2.INSTANCE_NUM);

/* Default initial setting for CUSTOM:OBSERVATION_INVALID_REASON modifier based on negative polarity */
insert into OBSERVATION_FACT
(MODIFIER_CD,VALTYPE_CD, TVAL_CHAR,CONCEPT_CD,PATIENT_NUM,ENCOUNTER_NUM,INSTANCE_NUM,OBSERVATION_BLOB,SOURCESYSTEM_CD,PROVIDER_ID)
SELECT 'CUSTOM:OBSERVATION_INVALID_REASON:','T','Negative Polarity',CONCEPT_CD,PATIENT_NUM,ENCOUNTER_NUM,INSTANCE_NUM,OBSERVATION_BLOB,SOURCESYSTEM_CD,PROVIDER_ID FROM OBSERVATION_FACT O1 WHERE MODIFIER_CD='CUSTOM:OBSERVATION_VALID:' and tval_char='-1'
and NOT EXISTS (SELECT * FROM OBSERVATION_FACT O2 where O1.ENCOUNTER_NUM=O2.ENCOUNTER_NUM AND O1.PATIENT_NUM=O2.PATIENT_NUM AND O1.CONCEPT_CD=O2.CONCEPT_CD AND O1.PROVIDER_ID=O2.PROVIDER_ID AND O2.MODIFIER_CD='CUSTOM:OBSERVATION_INVALID_REASON:' AND O2.VALTYPE_CD='T' AND O2.TVAL_CHAR='Negative Polarity' AND O1.INSTANCE_NUM=O2.INSTANCE_NUM);

/* Copy OBSERVATION_BLOB to CUSTOM:HIGHLIGHT: modifier */
insert into OBSERVATION_FACT
(MODIFIER_CD,VALTYPE_CD, TVAL_CHAR,CONCEPT_CD,PATIENT_NUM,ENCOUNTER_NUM,INSTANCE_NUM,SOURCESYSTEM_CD,PROVIDER_ID)
select 'CUSTOM:HIGHLIGHT:', 'T', OBSERVATION_BLOB,CONCEPT_CD,PATIENT_NUM,ENCOUNTER_NUM,INSTANCE_NUM,SOURCESYSTEM_CD,PROVIDER_ID from OBSERVATION_FACT O1 where OBSERVATION_BLOB is not null and modifier_cd='CUSTOM:SENT:'
and NOT EXISTS (SELECT * FROM OBSERVATION_FACT O2 where O1.ENCOUNTER_NUM=O2.ENCOUNTER_NUM AND O1.PATIENT_NUM=O2.PATIENT_NUM AND O1.CONCEPT_CD=O2.CONCEPT_CD AND O1.PROVIDER_ID=O2.PROVIDER_ID AND O2.MODIFIER_CD='CUSTOM:HIGHLIGHT:' AND O2.VALTYPE_CD='T' AND O1.INSTANCE_NUM=O2.INSTANCE_NUM);


/**
*
* Initialize PATIENT_VALID modifier for all concepts
*
*/
delete from OBSERVATION_FACT where MODIFIER_CD='CUSTOM:PATIENT_VALID:';

INSERT INTO OBSERVATION_FACT 
(MODIFIER_CD,VALTYPE_CD, TVAL_CHAR,CONCEPT_CD,PATIENT_NUM,ENCOUNTER_NUM,INSTANCE_NUM,SOURCESYSTEM_CD,PROVIDER_ID)
select distinct 'CUSTOM:PATIENT_VALID:','T','1',CONCEPT_CD,PATIENT_NUM,null,1,SOURCESYSTEM_CD,PROVIDER_ID from I2B2DEMODATA.OBSERVATION_FACT WHERE MODIFIER_CD='CUSTOM:OBSERVATION_VALID:';

UPDATE OBSERVATION_FACT O1 SET TVAL_CHAR='-1' WHERE MODIFIER_CD='CUSTOM:PATIENT_VALID:' 
AND NOT EXISTS (select * FROM OBSERVATION_FACT O2 where O1.CONCEPT_CD=O2.CONCEPT_CD AND O1.PATIENT_NUM=O2.PATIENT_NUM AND O2.MODIFIER_CD='CUSTOM:OBSERVATION_VALID:' AND O2.TVAL_CHAR='1');



/**
*
* PATIENT_VALID_FOR_CONCEPT  stored procedure - updates the PATIENT_VALID modifier for a given concept
*
**/
/
create or replace PROCEDURE PATIENT_VALID_FOR_CONCEPT (MY_CONCEPT_CD IN VARCHAR2) AS 

cnt INTEGER;
valid VARCHAR2(2);

BEGIN

FOR x IN (
  select distinct(PATIENT_NUM) from I2B2DEMODATA.OBSERVATION_FACT where CONCEPT_CD=MY_CONCEPT_CD and MODIFIER_CD='CUSTOM:OBSERVATION_VALID:' 
)

LOOP

select count(*) into cnt from I2B2DEMODATA.OBSERVATION_FACT where PATIENT_NUM=x.PATIENT_NUM and CONCEPT_CD=MY_CONCEPT_CD and MODIFIER_CD='CUSTOM:OBSERVATION_VALID:' and TVAL_CHAR='1';

if cnt > 0 then
valid := '1';
ELSE
valid := '-1';
END IF;

MERGE INTO I2B2DEMODATA.OBSERVATION_FACT obsf
USING (
  SELECT x.PATIENT_NUM PATIENT_NUM, MY_CONCEPT_CD CONCEPT_CD, 'CUSTOM:PATIENT_VALID:' MODIFIER_CD from dual
) u
ON (u.PATIENT_NUM = obsf.PATIENT_NUM and u.CONCEPT_CD = obsf.CONCEPT_CD and u.MODIFIER_CD = obsf.MODIFIER_CD)
WHEN MATCHED THEN 
UPDATE SET obsf.TVAL_CHAR = valid
WHEN NOT MATCHED THEN 
INSERT (PROVIDER_ID, PATIENT_NUM, CONCEPT_CD, INSTANCE_NUM, MODIFIER_CD, VALTYPE_CD, TVAL_CHAR) VALUES (0, x.PATIENT_NUM, MY_CONCEPT_CD, 1, 'CUSTOM:PATIENT_VALID:', 'T', valid);

commit;

END LOOP;

END;


/**
*
* PATIENT_COUNT_FOR_CONCEPT stored procedure - updates the patient count in the NodeMetaData table for a given concept
*
**/
/
create or replace PROCEDURE PATIENT_COUNT_FOR_CONCEPT (MY_CONCEPT_CD IN VARCHAR2) AS 

cnt INTEGER;

BEGIN

select count(distinct(PATIENT_NUM)) into cnt from I2B2DEMODATA.OBSERVATION_FACT
where CONCEPT_CD=MY_CONCEPT_CD
and MODIFIER_CD='CUSTOM:OBSERVATION_VALID:' 
and TVAL_CHAR='1';

MERGE INTO I2B2DEMODATA.NODE_METADATA nm
USING (
  SELECT CONCEPT_PATH, SUBSTR(CONCEPT_PATH,0,INSTR(CONCEPT_PATH,'\',-2)) PARENT_CONCEPT_PATH, 'PATIENT_COUNT' TYPE from CONCEPT_DIMENSION where CONCEPT_CD=MY_CONCEPT_CD
) u
ON (u.CONCEPT_PATH = nm.CONCEPT_PATH and u.PARENT_CONCEPT_PATH = nm.PARENT_CONCEPT_PATH and u.TYPE = nm.TYPE)
WHEN MATCHED THEN 
UPDATE SET nm.VALUE = cnt
WHEN NOT MATCHED THEN 
INSERT (CONCEPT_PATH, PARENT_CONCEPT_PATH, VALUE, TYPE) VALUES (u.CONCEPT_PATH, u.PARENT_CONCEPT_PATH, u.TYPE, cnt);

commit;

END;


