DROP TABLE PCORI_CDMV3.HARVEST;

CREATE TABLE PCORI_CDMV3.HARVEST(
  NETWORKID VARCHAR2(50),  
  NETWORK_NAME VARCHAR2(50),
  DATAMART_ID VARCHAR2(20),
  DATAMART_PLATFORM VARCHAR2(50),
  CDM_VERSION NUMBER(8),
  DATAMART_CLAIMS VARCHAR2(2), 
  DATAMART_EHR VARCHAR2(2), 
  BIRTH_DATE_MGMT VARCHAR2(2),
  ENR_START_DATE_MGMT VARCHAR2(2), 
  ENR_END_DATE_MGMT VARCHAR2(2), 
  ADMIT_DATE_MGMT VARCHAR2(2),
  DISCHARGE_DATE_MGMT VARCHAR2(2),
  PX_DATE_MGMT VARCHAR2(2),
  RX_ORDER_DATE_MGMT VARCHAR2(2), 
  RX_START_DATE_MGMT VARCHAR2(2), 
  RX_END_DATE_MGMT VARCHAR2(2), 
  DISPENSE_DATE_MGMT VARCHAR2(2), 
  LAB_ORDER_DATE_MGMT VARCHAR2(2), 
  SPECIMEN_DATE_MGMT VARCHAR2(2), 
  RESULT_DATE_MGMT VARCHAR2(2),
  MEASURE_DATE_MGMT VARCHAR2(2), 
  ONSET_DATE_MGMT VARCHAR2(2), 
  REPORT_DATE_MGMT VARCHAR2(2),
  RESOLVE_DATE_MGMT VARCHAR2(2), 
  PRO_DATE_MGMT VARCHAR2(2), 
  REFRESH_DEMOGRAPHIC_DATE DATE,
  REFRESH_ENROLLMENT_DATE DATE,
  REFRESH_ENCOUNTER_DATE DATE,
  REFRESH_DIAGNOSIS_DATE DATE,
  REFRESH_PROCEDURES_DATE DATE,  
  REFRESH_VITAL_DATE DATE, 
  REFRESH_DISPENSING_DATE DATE,  
  REFRESH_LAB_RESULT_CM_DATE DATE,  
  REFRESH_CONDITION_DATE DATE, 
  REFRESH_PRO_CM_DATE DATE,
  REFRESH_PRESCRIBING_DATE DATE,
  REFRESH_PCORNET_TRIAL_DATE DATE,
  REFRESH_DEATH_DATE DATE,
  REFRESH_DEATH_CAUSE_DATE DATE
);


INSERT INTO PCORI_CDMV3.HARVEST (
NETWORK_NAME, DATAMART_PLATFORM, CDM_VERSION,
DATAMART_CLAIMS, DATAMART_EHR, BIRTH_DATE_MGMT,
ENR_START_DATE_MGMT, ENR_END_DATE_MGMT, ADMIT_DATE_MGMT,
DISCHARGE_DATE_MGMT, PX_DATE_MGMT, RX_ORDER_DATE_MGMT, 
RX_START_DATE_MGMT, RX_END_DATE_MGMT, DISPENSE_DATE_MGMT, 
LAB_ORDER_DATE_MGMT, SPECIMEN_DATE_MGMT, RESULT_DATE_MGMT, 
MEASURE_DATE_MGMT, ONSET_DATE_MGMT, REPORT_DATE_MGMT, 
RESOLVE_DATE_MGMT, PRO_DATE_MGMT, REFRESH_DEMOGRAPHIC_DATE,
REFRESH_VITAL_DATE, 
REFRESH_CONDITION_DATE, REFRESH_PRO_CM_DATE
)
VALUES(
'PMS_DN', '02', 3,
'01', '02', '01', 
'01', '01', 'NI',
'NI', 'NI', 'NI',
'NI', 'NI', 'NI',
'NI', 'NI', 'NI',
'NI', 'NI', '01',
'NI', '01', SYSDATE, 
SYSDATE, 
SYSDATE, SYSDATE
);