/*** Mapping to Demographics ***/
 
CREATE TABLE PCORI_CDMV3.DEMOGRAPHIC 
(	
  PATID VARCHAR2(50 BYTE), 
	BIRTH_DATE VARCHAR2(10 BYTE), 
	BIRTH_TIME VARCHAR2(5 BYTE), 
	SEX VARCHAR2(2 BYTE), 
	HISPANIC VARCHAR2(2 BYTE), 
	RACE VARCHAR2(2 BYTE), 
	BIOBANK_FLAG VARCHAR2(1 BYTE), 
	RAW_SEX VARCHAR2(50 BYTE), 
	RAW_HISPANIC VARCHAR2(50 BYTE), 
	RAW_RACE VARCHAR2(50 BYTE)
);
   
INSERT /* APPEND NOLOGGING */ INTO PCORI_CDMV3.DEMOGRAPHIC 
SELECT DISTINCT 
  PATIENT_NUM, NULL, NULL, NULL, NULL, 
  NULL, NULL, SEX_CD, NULL,RACE_CD 
FROM 
  I2B2DEMODATA.PATIENT_DIMENSION 
  WHERE PATIENT_NUM IN 
  ( SELECT DISTINCT PATIENT_NUM
    FROM 
    I2B2DEMODATA.OBSERVATION_FACT 
    WHERE SOURCESYSTEM_CD IN ('HMS_PMS_REG_C01','HMS_PMS_REG_C00','HMS_PMS_REG_PRO', 'HMS_PMS_NLP_SNO', 'HMS_PMS_NLP_HPO', 'HMS_PMS_NLP_MSH', 'HMS_PMS_NLP_IC9', 'HMS_PMS_NLP_ICX')
  );
  
UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET SEX='F'
WHERE RAW_SEX='Female';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET SEX='M'
WHERE RAW_SEX='Male'; 

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET RACE='02'
WHERE RAW_RACE='Asian';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET HISPANIC='N', RAW_HISPANIC='N'
WHERE RAW_RACE='Asian';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET HISPANIC='N', RAW_HISPANIC='N'
WHERE RAW_RACE='Black (Not African American)';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET RACE='03'
WHERE RAW_RACE='Black (Not African American)';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET RACE='03'
WHERE RAW_RACE='Black (African American)';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET HISPANIC='N', RAW_HISPANIC='N'
WHERE RAW_RACE='Black (African American)';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET RACE='05'
WHERE RAW_RACE='Caucasian (Not Latino/Hispanic)';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET HISPANIC='N', RAW_HISPANIC='N'
WHERE RAW_RACE='Caucasian (Not Latino/Hispanic)';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET RACE='06'
WHERE RAW_RACE='Caucasian (Latino/Hispanic)';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET HISPANIC='Y', RAW_HISPANIC='Y'
WHERE RAW_RACE='Caucasian (Latino/Hispanic)';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET RACE='NI'
WHERE RAW_RACE='No information';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET HISPANIC='NI', RAW_HISPANIC='NI'
WHERE RAW_RACE='No information';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET RACE='OT'
WHERE RAW_RACE='Other';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET HISPANIC='OT', RAW_HISPANIC='OT'
WHERE RAW_RACE='Other';

UPDATE PCORI_CDMV3.DEMOGRAPHIC 
SET RAW_HISPANIC=RAW_RACE;  

/*** Mapping to PRO_CM ***/

CREATE TABLE PCORI_CDMV3.PRO_CM 
(	
  PRO_CM_ID VARCHAR2(200 BYTE), /* New Column */
  PATID VARCHAR2(20 BYTE), 
	ENCOUNTERID VARCHAR2(20 BYTE), 
	CM_ITEM VARCHAR2(20 BYTE), 
	CM_LOINC VARCHAR2(20 BYTE), 
	CM_DATE VARCHAR2(20 BYTE), 
	CM_TIME VARCHAR2(20 BYTE), 
	CM_RESPONSE NUMBER(38,0), 
	CM_METHOD VARCHAR2(20 BYTE), 
	CM_MODE VARCHAR2(20 BYTE), 
	CM_CAT VARCHAR2(20 BYTE), 
	RAW_CM_CODE VARCHAR2(20 BYTE), 
	RAW_CM_RESPONSE VARCHAR2(200 BYTE)
);
   
/* Create a PRO_CM Staging table which contains following fields where 
  c_basecode contains only the concept codes of 5 PRO being mapped out of 23 PRO 
  CM_ITEM, CM_LOINC, CM_RESPONSE, CM_METHOD, CM_MODE, CM_CAT contains the number's listed in PRO_CM table of PCORI_CDMV3 
*/
   
CREATE TABLE PCORI_CDMV3.PRO_CM_STAGING 
(	
  CM_ITEM VARCHAR2(20 BYTE), 
	CM_LOINC VARCHAR2(20 BYTE), 
	CM_RESPONSE NUMBER(38,0), 
	CM_METHOD VARCHAR2(20 BYTE), 
	CM_MODE VARCHAR2(20 BYTE), 
	CM_CAT VARCHAR2(20 BYTE), 
	C_BASECODE VARCHAR2(20 BYTE), 
	RAW_CM_RESPONSE VARCHAR2(200 BYTE)
);
   
INSERT /*+ APPEND NOLOGGING */ INTO PCORI_CDMV3.PRO_CM 
  SELECT 
    NULL, 
    ofact.patient_num, null, b.cm_item, b.cm_loinc, null, null, b.cm_response,
    b.cm_method, b.cm_mode, b.cm_cat, null, b.raw_cm_response
   FROM
    (I2B2DEMODATA.OBSERVATION_FACT)ofact,
    (PCORI_CDMV3.PRO_CM_STAGING)b
   WHERE 
    ofact.concept_cd=b.c_basecode;
   
/*** Mapping Condition table ***/
   
/* Instead of Diagnosis for our PPRN Condition table should be mapped */
CREATE TABLE PCORI_CDMV3.DIAGNOSIS
(
  DIAGNOSIS_ID VARCHAR2(200),  /*NEW COLUMN*/
  PATID VARCHAR2(50),
  ENCOUNTERID VARCHAR2(50),
  ENC_TYPE VARCHAR2(50),
  ADMIT_DATE VARCHAR2(50),
  PROVIDERID VARCHAR2(50),
  DX VARCHAR2(500),
  DX_TYPE VARCHAR2(50),
  DX_SOURCE VARCHAR2(50),
  PDX VARCHAR2(50),
  RAW_DX VARCHAR2(500),
  RAW_DX_TYPE VARCHAR2(50),
  RAW_DX_SOURCE VARCHAR2(50),
  RAW_PDX VARCHAR2(50)
);

INSERT  /*+ APPEND NOLOGGING */ INTO PCORI_CDMV3.DIAGNOSIS
  SELECT DISTINCT 
    NULL,
    patient_num, encounter_num, 'OT', null, null, concept_cd, '09',
    'OT', 'OT', CONCEPT_CD, '09', 'OT', 'OT' 
  FROM observation_fact 
  WHERE sourcesystem_cd LIKE 'ICD9%';

INSERT /*+ APPEND NOLOGGING */  INTO PCORI_CDMV3.DIAGNOSIS
  SELECT DISTINCT 
    NULL,
    patient_num, encounter_num, 'OT', null, null, substr(concept_cd,5), 'SM',
    'OT', 'OT', substr(concept_cd,5), 'SM', 'OT', 'OT' 
  FROM observation_fact 
  WHERE sourcesystem_cd LIKE 'SNOMED%' AND concept_cd LIKE 'SNO:%';

INSERT /*+ APPEND NOLOGGING */  INTO PCORI_CDMV3.DIAGNOSIS
  SELECT DISTINCT 
    NULL,
    patient_num, encounter_num, 'OT', null, null, substr(concept_cd,4), 'OT',
    'OT', 'OT', substr(concept_cd,4), 'OT', 'OT', 'OT' 
  FROM observation_fact 
  WHERE sourcesystem_cd LIKE 'HPO%';

CREATE TABLE PCORI_CDMV3.CONDITION
(
    CONDITION_ID VARCHAR2(50),  /* New Column*/
	  PATID VARCHAR2(50),
	  ENCOUNTERID VARCHAR2(50),
	  REPORT_DATE VARCHAR2(50),
	  RESOLVE_DATE VARCHAR2(50),
    ONSET_DATE VARCHAR2(50),   
	  CONDITION_STATUS VARCHAR2(2),
	  CONDITION VARCHAR2(18),
	  CONDITION_TYPE VARCHAR2(2),
	  CONDITION_SOURCE VARCHAR2(2),
	  RAW_CONIDITION_STATUS VARCHAR2(50),
	  RAW_CONDIITON VARCHAR2(50),
	  RAW_CONDIITON_TYPE VARCHAR2(50),
	  RAW_CONDITION_SOURCE VARCHAR2(50)
);   
	  
INSERT /*+ APPEND NOLOGGING */  INTO PCORI_CDMV3.CONDITION
  SELECT DISTINCT 
    NULL,
    patient_num, encounter_num, null, null, NULL, null, 
    concept_cd, '09', null, null, null, null, null 
  FROM observation_fact WHERE sourcesystem_cd like 'ICD9%';

INSERT /*+ APPEND NOLOGGING */  INTO PCORI_CDMV3.CONDITION
  SELECT DISTINCT 
    NULL, 
    patient_num, encounter_num, null, null, NULL, null,
    concept_cd, 'SM', null, null, null, null, null 
  FROM observation_fact WHERE sourcesystem_cd like 'SNOMED%';
	 
INSERT /*+ APPEND NOLOGGING */ INTO PCORI_CDMV3.CONDITION
  SELECT DISTINCT 
    NULL, 
    patient_num, encounter_num, null, null, NULL, null,
    concept_cd, 'OT', null, null, null, null, null 
  FROM observation_fact WHERE sourcesystem_cd like 'HPO%';
 
/** New DISPENSING table **/ 
CREATE TABLE PCORI_CDMV3.DISPENSING 
(
  DISPENSING_ID VARCHAR2(20), 
  PATID VARCHAR2(20), 
  PRESCRIBING_ID VARCHAR2(20), 
  DISPENSE_DATE VARCHAR2(20), 
  NDC VARCHAR2(11), 
  DISPENSE_SUP VARCHAR2(8), 
  DISPENSE_AMT VARCHAR2(8), 
  RAW_NDC VARCHAR2(50)
); 

CREATE TABLE PCORI_CDMV3.DEATH 
(
  PATID VARCHAR2(20), 
  DEATH_DATE VARCHAR2(20), 
  DEATH_SOURCE VARCHAR2(2), 
  DEATH_DATE_IMPUTE VARCHAR2(2), 
  DEATH_MATCH_CONFIDENCE VARCHAR2(2)
);

CREATE TABLE PCORI_CDMV3.DEATH_CAUSE 
(
  PATID VARCHAR2(20), 
  DEATH_CAUSE VARCHAR2(8),  
  DEATH_CAUSE_CODE VARCHAR2(2),  
  DEATH_CAUSE_TYPE VARCHAR2(2), 
  DEATH_CAUSE_SOURCE VARCHAR2(2),  
  DEATH_CAUSE_CONFIDENCE VARCHAR2(2) 
 ); 
 
CREATE TABLE PCORI_CDMV3.ENCOUNTER 
(
  ENCOUNTER_ID VARCHAR2(20), 
  PATID VARCHAR2(20), 
  ADMIT_DATE VARCHAR2(6), 
  ENC_TYPE VARCHAR2(2), 
  ADMIT_TIME VARCHAR2(5), 
  DISCHARGE_DATE VARCHAR2(6), 
  DISCHARGE_TIME VARCHAR2(5), 
  PROVIDER_ID VARCHAR2(20), 
  FACILITY_LOCATION VARCHAR2(20), 
  FACILITY_ID VARCHAR2(20), 
  DISCHARGE_DISPOSITION VARCHAR2(2), 
  DISCHARGE_STATUS VARCHAR2(2), 
  DRG VARCHAR2(3), 
  DRG_TYPE VARCHAR2(2), 
  ADMITTING_SOURCE VARCHAR2(2), 
  RAW_SITEID VARCHAR2(50), 
  RAW_ENC_TYPE VARCHAR2(50),
  RAW_DISCHARGE_DISPOSITION VARCHAR2(50), 
  RAW_DRG_TYPE VARCHAR2(50), 
  RAW_DISCHARGE_STATUS VARCHAR2(50), 
  RAW_ADMITTING_SOURCE VARCHAR2(50)
);

CREATE TABLE PCORI_CDMV3.ENROLLMENT 
(
  PATID VARCHAR2(20), 
  ENR_BASIS VARCHAR2(1), 
  ENR_START_DATE VARCHAR2(6), 
  CHART VARCHAR2(1), 
  ENR_END_DATE TIMESTAMP(6) 
);

CREATE TABLE PCORI_CDMV3.LAB_RESULT_CM 
(
  LAB_RESULT_CM_ID VARCHAR2(20), 
  PATID VARCHAR2(20), 
  ENCOUNTER_ID VARCHAR2(20), 
  RESULT_DATE VARCHAR2(20), 
  LAB_NAME VARCHAR2(10), 
  SPECIMEN_SOURCE VARCHAR2(10), 
  LAB_LOINC VARCHAR2(10), 
  PRIORITY VARCHAR2(2), 
  RESULT_LOC VARCHAR2(2), 
  LAB_PX VARCHAR2(11), 
  LAB_PX_TYPE VARCHAR2(2), 
  LAB_ORDER_DATE DATE, 
  SPECIMEN_DATE DATE, 
  SPECIMEN_TIME VARCHAR2(5), 
  RESULT_TIME VARCHAR2(5), 
  RESULT_QUAL VARCHAR2(12), 
  RESULT_NUM NUMBER(8), 
  RESULT_MODIFIER VARCHAR2(2), 
  RESULT_UNIT VARCHAR2(11), 
  NORM_RANGE_LOW VARCHAR2(10), 
  NORM_MODIFIER_LOW VARCHAR2(2), 
  NORM_RANGE_HIGH VARCHAR2(10), 
  NORM_MODIFIER_HIGH VARCHAR2(2), 
  ABN_IND VARCHAR2(2), 
  RAW_LAB_NAME VARCHAR2(20), 
  RAW_LAB_CODE VARCHAR2(20),
  RAW_PANEL VARCHAR2(20), 
  RAW_RESULT VARCHAR2(20), 
  RAW_UNIT VARCHAR2(20), 
  RAW_ORDER_DEPT VARCHAR2(20), 
  RAW_FACILITY_CODE VARCHAR2(20)
);

CREATE TABLE PCORI_CDMV3.PCORNET_TRIAL 
(
  TRIAL_ID VARCHAR2(20), 
  PATID VARCHAR2(20), 
  PARTICIPANT_ID VARCHAR2(20), 
  TRIAL_SITE_ID VARCHAR2(20), 
  TRIAL_ENROLL_DATE VARCHAR2(10), 
  TRIAL_END_DATE VARCHAR2(10), 
  TRIAL_WITHDRAW_DATE VARCHAR2(20), 
  TRIAL_INVITE_CODE VARCHAR2(20) 
);

CREATE TABLE PCORI_CDMV3.PRESCRIBING
(
  PRESCRIBING_ID VARCHAR2(20), 
  PATID VARCHAR2(20), 
  ENCOUNTER_ID VARCHAR2(20),  
  RX_PROVIDER_ID VARCHAR2(20), 
  RX_ORDER_DATE VARCHAR2(10),  
  RX_ORDER_TIME VARCHAR2(5), 
  RX_START_DATE VARCHAR2(10),
  RX_END_DATE VARCHAR2(10),
  RX_QUANTITY VARCHAR2(8),
  RX_REFILLS VARCHAR2(8),
  RX_DAYS_SUPPLY VARCHAR2(8),
  RX_FREQUENCY VARCHAR2(2),
  RX_BASIS VARCHAR2(2),
  RXNORM_CUI VARCHAR2(8),
  RAW_RX_MED_NAME VARCHAR2(20), 
  RAW_RX_FREQUENCY VARCHAR2(20),
  RAW_RXNORM_CUI VARCHAR2(20)
);

CREATE TABLE PCORI_CDMV3.PROCEDURES 
(
  PROCEDURES_ID VARCHAR2(20) 
, PATID VARCHAR2(20) 
, ENCOUNTER_ID VARCHAR2(20) 
, PX VARCHAR2(20) 
, PX_TYPE VARCHAR2(2) 
, ENC_TYPE VARCHAR2(2) 
, ADMIT_TYPE VARCHAR2(10) 
, PROVIDER_ID VARCHAR2(20) 
, PX_DATE VARCHAR2(20)
, PX_SOURCE VARCHAR2(20) 
, RAW_PX VARCHAR2(20) 
, RAW_PX_TYPE VARCHAR2(20) 
);

DROP TABLE PCORI_CDMV3.VITAL;

CREATE TABLE PCORI_CDMV3.VITAL 
(
  VITALID VARCHAR2(50) 
, PATID VARCHAR2(20) 
, ENCOUNTER_ID VARCHAR2(20) 
, MEASURE_DATE VARCHAR2(20) 
, VITAL_SOURCE VARCHAR2(2) 
, MEASURE_TIME VARCHAR2(5) 
, HT VARCHAR2(20) 
, WT VARCHAR2(20) 
, DIASTOLIC VARCHAR2(10) 
, SYSTOLIC VARCHAR2(10) 
, ORIGINAL_BMI VARCHAR2(10) 
, BP_POSITION VARCHAR2(2) 
, SMOKING VARCHAR2(2)
, TOBACCO VARCHAR2(2)
, TOBACCO_TYPE VARCHAR2(2)
, RAW_DIASTOLIC VARCHAR2(20)
, RAW_SYSTOLIC VARCHAR2(20)
, RAW_BP_POSITION VARCHAR2(20)
, RAW_SMOKING VARCHAR2(20)
, RAW_TOBACCO VARCHAR2(20)
, RAW_TOBACCO_TYPE VARCHAR2(20)
);

CREATE TABLE PCORI_CDMV3.VITAL_STAGING
(
  PATID VARCHAR2(20)
, ATTR VARCHAR2(200)
, HT VARCHAR2(20) 
, WT VARCHAR2(20) 
, DIASTOLIC VARCHAR2(10) 
, SYSTOLIC VARCHAR2(10) 
, ORIGINAL_BMI VARCHAR2(10) 
, BP_POSITION VARCHAR2(2) 
, SMOKING VARCHAR2(2)
, TOBACCO VARCHAR2(2)
, TOBACCO_TYPE VARCHAR2(2)
);


DROP TABLE PCORI_CDMV3.VITAL_STAGING;

INSERT INTO PCORI_CDMV3.VITAL_STAGING (PATID, ATTR, HT)
SELECT OBFA.PATIENT_NUM, OBFA.CONCEPT_CD, OBFA.TVAL_CHAR
FROM 
(I2B2DEMODATA.OBSERVATION_FACT) OBFA,
(I2B2METADATA.I2B2) I2B2
WHERE 
OBFA.CONCEPT_CD = I2B2.C_BASECODE AND
REGEXP_LIKE (I2B2.C_FULLNAME, '^\\DBMI\\PMS_DN\\01 PMS Registry \(Patient Reported Outcomes\)\\01 PMS Patient Reported Outcomes\\Clinical\\General Information\\.*height\? \\currently\\.*$') 
ORDER BY PATIENT_NUM, CONCEPT_CD
;

INSERT INTO PCORI_CDMV3.VITAL_STAGING (PATID, ATTR, WT)
SELECT OBFA.PATIENT_NUM, OBFA.CONCEPT_CD, OBFA.TVAL_CHAR
FROM 
(I2B2DEMODATA.OBSERVATION_FACT) OBFA,
(I2B2METADATA.I2B2) I2B2
WHERE 
OBFA.CONCEPT_CD = I2B2.C_BASECODE AND
REGEXP_LIKE (I2B2.C_FULLNAME, '^\\DBMI\\PMS_DN\\01 PMS Registry \(Patient Reported Outcomes\)\\01 PMS Patient Reported Outcomes\\Clinical\\General Information\\.*weight\? \\currently\\.*$') 
ORDER BY PATIENT_NUM, CONCEPT_CD
;

INSERT INTO PCORI_CDMV3.VITAL (VITALID, PATID, WT)
SELECT 
'VITAL:' || PATID || '_' || ATTR, PATID, WT
FROM 
PCORI_CDMV3.VITAL_STAGING
WHERE 
WT IS NOT NULL;

INSERT INTO PCORI_CDMV3.VITAL (VITALID, PATID, HT)
SELECT 
'VITAL:' || PATID || '_' || ATTR, PATID, HT
FROM 
PCORI_CDMV3.VITAL_STAGING
WHERE 
HT IS NOT NULL;
