DROP TABLE pCORI_CDMV3.DISPENSING;
COMMIT;

CREATE TABLE PCORI_CDMV3.DISPENSING_STAGING (
  PATIENT_NUM VARCHAR2(20 BYTE),
  NDC VARCHAR2(11 BYTE)
);
COMMIT;

INSERT /*+ APPEND NOLOGGING */ 
INTO PCORI_CDMV3.DISPENSING_STAGING
SELECT DISTINCT 
ob.patient_num, 
i2.c_basecode
FROM 
i2b2demodata.observation_fact ob,
i2b2metadata.i2b2 i2 
WHERE
ob.concept_cd = i2.C_BASECODE
and ob.sourcesystem_cd = 'HMS_PMS_NLP_NDT' 
and i2.c_hlevel > 4 
ORDER BY ob.PATIENT_NUM;
COMMIT;

CREATE TABLE PCORI_CDMV3.DISPENSING
(
  DISPENSING_ID VARCHAR2(20),
  PATID VARCHAR2(20),
  PRESCRIBING_ID VARCHAR2(20),
  DISPENSE_DATE VARCHAR2(20),
  NDC VARCHAR2(11),
  DISPENSE_SUP VARCHAR2(8),
  DISPENSE_AMT VARCHAR2(8),
  RAW_NDC VARCHAR2(50)
);
COMMIT;

INSERT /*+ APPEND NOLOGGING */ 
INTO PCORI_CDMV3.DISPENSING 
SELECT 
PATIENT_NUM || '_' || NDC,
PATIENT_NUM,
NULL,
TO_CHAR(SYSDATE), 
NDC,
NULL, 
NULL, 
NULL
FROM 
PCORI_CDMV3.DISPENSING_STAGING;
COMMIT;

DROP TABLE pCORI_CDMV3.DISPENSING_STAGING;
COMMIT;