DROP TABLE SCILHS.DEMOGRAPHIC;

CREATE TABLE SCILHS.DEMOGRAPHIC 
(	
  PATID VARCHAR2(50 BYTE), 
	BIRTH_DATE VARCHAR2(10 BYTE), 
	BIRTH_TIME VARCHAR2(5 BYTE), 
	SEX VARCHAR2(2 BYTE), 
	HISPANIC VARCHAR2(2 BYTE), 
	RACE VARCHAR2(2 BYTE), 
	BIOBANK_FLAG VARCHAR2(1 BYTE), 
	RAW_SEX VARCHAR2(50 BYTE), 
	RAW_HISPANIC VARCHAR2(50 BYTE), 
	RAW_RACE VARCHAR2(50 BYTE)
);

INSERT /* APPEND NOLOGGING */ INTO SCILHS.DEMOGRAPHIC 
SELECT DISTINCT 
  PATIENT_NUM, NULL, NULL, NULL, NULL, 
  NULL, NULL, SEX_CD, NULL,RACE_CD 
FROM 
  I2B2DEMODATA.PATIENT_DIMENSION 
  WHERE PATIENT_NUM IN 
  ( SELECT DISTINCT PATIENT_NUM
    FROM 
    I2B2DEMODATA.OBSERVATION_FACT 
    WHERE SOURCESYSTEM_CD IN ('HMS_PMS_REG_C01','HMS_PMS_REG_C00','HMS_PMS_REG_PRO', 'HMS_PMS_NLP_SNO', 'HMS_PMS_NLP_HPO', 'HMS_PMS_NLP_MSH', 'HMS_PMS_NLP_IC9', 'HMS_PMS_NLP_ICX')
  );
  
UPDATE SCILHS.DEMOGRAPHIC 
SET SEX='F'
WHERE RAW_SEX='Female';

UPDATE SCILHS.DEMOGRAPHIC 
SET SEX='M'
WHERE RAW_SEX='Male'; 

UPDATE SCILHS.DEMOGRAPHIC 
SET RACE='02'
WHERE RAW_RACE='Asian';

UPDATE SCILHS.DEMOGRAPHIC 
SET HISPANIC='N', RAW_HISPANIC='N'
WHERE RAW_RACE='Asian';

UPDATE SCILHS.DEMOGRAPHIC 
SET HISPANIC='N', RAW_HISPANIC='N'
WHERE RAW_RACE='Black (Not African American)';

UPDATE SCILHS.DEMOGRAPHIC 
SET RACE='03'
WHERE RAW_RACE='Black (Not African American)';

UPDATE SCILHS.DEMOGRAPHIC 
SET RACE='03'
WHERE RAW_RACE='Black (African American)';

UPDATE SCILHS.DEMOGRAPHIC 
SET HISPANIC='N', RAW_HISPANIC='N'
WHERE RAW_RACE='Black (African American)';

UPDATE SCILHS.DEMOGRAPHIC 
SET RACE='05'
WHERE RAW_RACE='Caucasian (Not Latino/Hispanic)';

UPDATE SCILHS.DEMOGRAPHIC 
SET HISPANIC='N', RAW_HISPANIC='N'
WHERE RAW_RACE='Caucasian (Not Latino/Hispanic)';

UPDATE SCILHS.DEMOGRAPHIC 
SET RACE='06'
WHERE RAW_RACE='Caucasian (Latino/Hispanic)';

UPDATE SCILHS.DEMOGRAPHIC 
SET HISPANIC='Y', RAW_HISPANIC='Y'
WHERE RAW_RACE='Caucasian (Latino/Hispanic)';

UPDATE SCILHS.DEMOGRAPHIC 
SET RACE='NI'
WHERE RAW_RACE='No information';

UPDATE SCILHS.DEMOGRAPHIC 
SET HISPANIC='NI', RAW_HISPANIC='NI'
WHERE RAW_RACE='No information';

UPDATE SCILHS.DEMOGRAPHIC 
SET RACE='OT'
WHERE RAW_RACE='Other';

UPDATE SCILHS.DEMOGRAPHIC 
SET HISPANIC='OT', RAW_HISPANIC='OT'
WHERE RAW_RACE='Other';

UPDATE SCILHS.DEMOGRAPHIC 
SET RAW_HISPANIC=RAW_RACE;  

COMMIT;

DROP TABLE SCILHS.VITAL;

CREATE TABLE SCILHS.VITAL 
(
  VITALID VARCHAR2(50) 
, PATID VARCHAR2(20) 
, ENCOUNTER_ID VARCHAR2(20) 
, MEASURE_DATE VARCHAR2(20) 
, VITAL_SOURCE VARCHAR2(2) 
, MEASURE_TIME VARCHAR2(5) 
, HT VARCHAR2(20) 
, WT VARCHAR2(20) 
, DIASTOLIC VARCHAR2(10) 
, SYSTOLIC VARCHAR2(10) 
, ORIGINAL_BMI VARCHAR2(10) 
, BP_POSITION VARCHAR2(2) 
, SMOKING VARCHAR2(2)
, TOBACCO VARCHAR2(2)
, TOBACCO_TYPE VARCHAR2(2)
, RAW_DIASTOLIC VARCHAR2(20)
, RAW_SYSTOLIC VARCHAR2(20)
, RAW_BP_POSITION VARCHAR2(20)
, RAW_SMOKING VARCHAR2(20)
, RAW_TOBACCO VARCHAR2(20)
, RAW_TOBACCO_TYPE VARCHAR2(20)
);

COMMIT;

CREATE TABLE SCILHS.VITAL_HT
(
  PATID VARCHAR2(20),
  HT VARCHAR2(20),
  MEASURE_DATE VARCHAR2(20)
);

CREATE TABLE SCILHS.VITAL_WT
(
  PATID VARCHAR2(20),
  WT VARCHAR2(20) 
);

INSERT INTO SCILHS.VITAL_HT(PATID, HT, MEASURE_DATE)
SELECT 
OBFA.PATIENT_NUM, OBFA.TVAL_CHAR, OBFA.IMPORT_DATE
FROM 
(I2B2DEMODATA.OBSERVATION_FACT) OBFA,
(I2B2METADATA.I2B2) I2B2
WHERE 
OBFA.CONCEPT_CD = I2B2.C_BASECODE AND
REGEXP_LIKE (I2B2.C_FULLNAME, '^\\DBMI\\PMS_DN\\01 PMS Registry \(Patient Reported Outcomes\)\\01 PMS Patient Reported Outcomes\\Clinical\\General Information\\.*height\? \\currently\\.*$')
;

INSERT INTO SCILHS.VITAL_WT(PATID, WT)
SELECT 
OBFA.PATIENT_NUM, OBFA.TVAL_CHAR
FROM 
(I2B2DEMODATA.OBSERVATION_FACT) OBFA,
(I2B2METADATA.I2B2) I2B2
WHERE 
OBFA.CONCEPT_CD = I2B2.C_BASECODE AND
REGEXP_LIKE (I2B2.C_FULLNAME, '^\\DBMI\\PMS_DN\\01 PMS Registry \(Patient Reported Outcomes\)\\01 PMS Patient Reported Outcomes\\Clinical\\General Information\\.*weight\? \\currently\\.*$')
;

INSERT INTO SCILHS.VITAL(VITALID, VITAL_SOURCE, PATID, HT, WT, MEASURE_DATE)
SELECT 
VH.PATID || '_' || VH.MEASURE_DATE, 
'PR',
VH.PATID, VH.HT, VW.WT, VH.MEASURE_DATE
FROM 
(SCILHS.VITAL_HT) VH JOIN (SCILHS.VITAL_WT) VW
ON 
VW.PATID = VH.PATID;

COMMIT;

DROP TABLE SCILHS.VITAL_HT;
DROP TABLE SCILHS.VITAL_WT;
COMMIT;


DROP TABLE SCILHS.VITAL;

CREATE TABLE SCILHS.VITAL 
(
  VITALID VARCHAR2(50) 
, PATID VARCHAR2(20) 
, ENCOUNTER_ID VARCHAR2(20) 
, MEASURE_DATE VARCHAR2(20) 
, VITAL_SOURCE VARCHAR2(2) 
, MEASURE_TIME VARCHAR2(5) 
, HT VARCHAR2(20) 
, WT VARCHAR2(20) 
, DIASTOLIC VARCHAR2(10) 
, SYSTOLIC VARCHAR2(10) 
, ORIGINAL_BMI VARCHAR2(10) 
, BP_POSITION VARCHAR2(2) 
, SMOKING VARCHAR2(2)
, TOBACCO VARCHAR2(2)
, TOBACCO_TYPE VARCHAR2(2)
, RAW_DIASTOLIC VARCHAR2(20)
, RAW_SYSTOLIC VARCHAR2(20)
, RAW_BP_POSITION VARCHAR2(20)
, RAW_SMOKING VARCHAR2(20)
, RAW_TOBACCO VARCHAR2(20)
, RAW_TOBACCO_TYPE VARCHAR2(20)
);

COMMIT;

CREATE TABLE SCILHS.VITAL_HT
(
  PATID VARCHAR2(20),
  HT VARCHAR2(20),
  MEASURE_DATE VARCHAR2(20)
);

CREATE TABLE SCILHS.VITAL_WT
(
  PATID VARCHAR2(20),
  WT VARCHAR2(20) 
);

INSERT INTO SCILHS.VITAL_HT(PATID, HT, MEASURE_DATE)
SELECT 
OBFA.PATIENT_NUM, OBFA.TVAL_CHAR, OBFA.IMPORT_DATE
FROM 
(I2B2DEMODATA.OBSERVATION_FACT) OBFA,
(I2B2METADATA.I2B2) I2B2
WHERE 
OBFA.CONCEPT_CD = I2B2.C_BASECODE AND
REGEXP_LIKE (I2B2.C_FULLNAME, '^\\DBMI\\PMS_DN\\01 PMS Registry \(Patient Reported Outcomes\)\\01 PMS Patient Reported Outcomes\\Clinical\\General Information\\.*height\? \\currently\\.*$')
;

INSERT INTO SCILHS.VITAL_WT(PATID, WT)
SELECT 
OBFA.PATIENT_NUM, OBFA.TVAL_CHAR
FROM 
(I2B2DEMODATA.OBSERVATION_FACT) OBFA,
(I2B2METADATA.I2B2) I2B2
WHERE 
OBFA.CONCEPT_CD = I2B2.C_BASECODE AND
REGEXP_LIKE (I2B2.C_FULLNAME, '^\\DBMI\\PMS_DN\\01 PMS Registry \(Patient Reported Outcomes\)\\01 PMS Patient Reported Outcomes\\Clinical\\General Information\\.*weight\? \\currently\\.*$')
;

INSERT INTO SCILHS.VITAL(VITALID, VITAL_SOURCE, PATID, HT, WT, MEASURE_DATE)
SELECT 
VH.PATID || '_' || VH.MEASURE_DATE, 
'PR',
VH.PATID, VH.HT, VW.WT, VH.MEASURE_DATE
FROM 
(SCILHS.VITAL_HT) VH JOIN (SCILHS.VITAL_WT) VW
ON 
VW.PATID = VH.PATID;

COMMIT;

DROP TABLE SCILHS.VITAL_HT;
DROP TABLE SCILHS.VITAL_WT;
COMMIT;