--------------------------------------------------------
--  File created - Wednesday-June-17-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRO_CM_STAGING
--------------------------------------------------------

  CREATE TABLE "PCORI_CDMV2"."PRO_CM_STAGING" 
   (	"CM_ITEM" VARCHAR2(20 BYTE), 
	"CM_LOINC" VARCHAR2(20 BYTE), 
	"CM_RESPONSE" NUMBER(38,0), 
	"CM_METHOD" VARCHAR2(20 BYTE), 
	"CM_MODE" VARCHAR2(20 BYTE), 
	"CM_CAT" VARCHAR2(20 BYTE), 
	"C_BASECODE" VARCHAR2(20 BYTE), 
	"RAW_CM_RESPONSE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ;

REM INSERTING into PCORI_CDMV2.PRO_CM_STAGING
SET DEFINE OFF;
--Insert into PCORI_CDMV2.PRO_CM_STAGING (CM_ITEM,CM_LOINC,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,C_BASECODE,RAA');
Insert into PCORI_CDMV2.PRO_CM_STAGING (CM_ITEM,CM_LOINC,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,C_BASECODE,RAW_CM_RESPONSE) values ('PN_0012','75416-8',4,'EC','PR','N','103655','The patient has been diagnosed with depression or bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM_STAGING (CM_ITEM,CM_LOINC,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,C_BASECODE,RAW_CM_RESPONSE) values ('PN_0005','61967-6',5,'EC','PR','N','103661','The patient has been diagnosed with depression or bipolar/manic depression ');
Insert into PCORI_CDMV2.PRO_CM_STAGING (CM_ITEM,CM_LOINC,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,C_BASECODE,RAW_CM_RESPONSE) values ('PN_0005','61967-6',1,'EC','PR','N','103662','The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM_STAGING (CM_ITEM,CM_LOINC,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,C_BASECODE,RAW_CM_RESPONSE) values ('PN_0006','61998-1',1,'EC','PR','N','103659','The patient never experienced any of these symptoms neither insomnia ');
Insert into PCORI_CDMV2.PRO_CM_STAGING (CM_ITEM,CM_LOINC,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,C_BASECODE,RAW_CM_RESPONSE) values ('PN_0006','61998-1',5,'EC','PR','N','103647','The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM_STAGING (CM_ITEM,CM_LOINC,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,C_BASECODE,RAW_CM_RESPONSE) values ('PN_0007','75417-6',3,'EC','PR','N','103653','The patient''s interest in social interaction increased in adulthood');
Insert into PCORI_CDMV2.PRO_CM_STAGING (CM_ITEM,CM_LOINC,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,C_BASECODE,RAW_CM_RESPONSE) values ('PN_0007','75417-6',2,'EC','PR','N','103667','The patient''s interest in social interaction decreased in adulthood');
Insert into PCORI_CDMV2.PRO_CM_STAGING (CM_ITEM,CM_LOINC,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,C_BASECODE,RAW_CM_RESPONSE) values ('PN_0017','61949-4',1,'EC','PR','N','103663','The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV2.PRO_CM_STAGING (CM_ITEM,CM_LOINC,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,C_BASECODE,RAW_CM_RESPONSE) values ('PN_0017','61949-4',5,'EC','PR','N','103656','The patient has been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder; or the patient repeatedly exhibited anxiety');

--------------------------------------------------------
--  File created - Tuesday-August-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRO_CM
--------------------------------------------------------

  CREATE TABLE "PCORI_CDMV2"."PRO_CM" 
   (	"PATID" VARCHAR2(20 BYTE), 
	"ENCOUNTERID" VARCHAR2(20 BYTE), 
	"CM_ITEM" VARCHAR2(20 BYTE), 
	"CM_LOINC" VARCHAR2(20 BYTE), 
	"CM_DATE" VARCHAR2(20 BYTE), 
	"CM_TIME" VARCHAR2(20 BYTE), 
	"CM_RESPONSE" NUMBER(38,0), 
	"CM_METHOD" VARCHAR2(20 BYTE), 
	"CM_MODE" VARCHAR2(20 BYTE), 
	"CM_CAT" VARCHAR2(20 BYTE), 
	"RAW_CM_CODE" VARCHAR2(20 BYTE), 
	"RAW_CM_RESPONSE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ;

REM INSERTING into PCORI_CDMV2.PRO_CM
SET DEFINE OFF;
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1886',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1947',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1949',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2003',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2030',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1903',null,'PN_0012','75416-8',null,null,4,'EC','PR','N',null,'The patient has been diagnosed with depression or bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1911',null,'PN_0005','61967-6',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with depression or bipolar/manic depression ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1955',null,'PN_0005','61967-6',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with depression or bipolar/manic depression ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1869',null,'PN_0006','61998-1',null,null,1,'EC','PR','N',null,'The patient never experienced any of these symptoms neither insomnia ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1888',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1912',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1914',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1955',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1956',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1981',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1972',null,'PN_0007','75417-6',null,null,3,'EC','PR','N',null,'The patient''s interest in social interaction increased in adulthood');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1913',null,'PN_0017','61949-4',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2039',null,'PN_0017','61949-4',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1889',null,'PN_0017','61949-4',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder; or the patient repeatedly exhibited anxiety');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1895',null,'PN_0017','61949-4',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder; or the patient repeatedly exhibited anxiety');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1917',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1921',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1988',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1997',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1890',null,'PN_0005','61967-6',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with depression or bipolar/manic depression ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2002',null,'PN_0005','61967-6',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with depression or bipolar/manic depression ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1889',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1892',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1998',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2023',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1928',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1954',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2020',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1913',null,'PN_0007','75417-6',null,null,3,'EC','PR','N',null,'The patient''s interest in social interaction increased in adulthood');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2034',null,'PN_0007','75417-6',null,null,3,'EC','PR','N',null,'The patient''s interest in social interaction increased in adulthood');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1955',null,'PN_0007','75417-6',null,null,2,'EC','PR','N',null,'The patient''s interest in social interaction decreased in adulthood');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1898',null,'PN_0017','61949-4',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1975',null,'PN_0017','61949-4',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2017',null,'PN_0017','61949-4',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder; or the patient repeatedly exhibited anxiety');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2037',null,'PN_0017','61949-4',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder; or the patient repeatedly exhibited anxiety');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1922',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1931',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1978',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2024',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2029',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1914',null,'PN_0005','61967-6',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with depression or bipolar/manic depression ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1974',null,'PN_0005','61967-6',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with depression or bipolar/manic depression ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1954',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1889',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1913',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1998',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1891',null,'PN_0007','75417-6',null,null,3,'EC','PR','N',null,'The patient''s interest in social interaction increased in adulthood');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1912',null,'PN_0007','75417-6',null,null,3,'EC','PR','N',null,'The patient''s interest in social interaction increased in adulthood');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1957',null,'PN_0017','61949-4',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2004',null,'PN_0017','61949-4',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder; or the patient repeatedly exhibited anxiety');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2033',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2037',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1891',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1912',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1916',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2021',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2026',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2002',null,'PN_0007','75417-6',null,null,3,'EC','PR','N',null,'The patient''s interest in social interaction increased in adulthood');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1914',null,'PN_0007','75417-6',null,null,2,'EC','PR','N',null,'The patient''s interest in social interaction decreased in adulthood');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1977',null,'PN_0017','61949-4',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1921',null,'PN_0017','61949-4',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder; or the patient repeatedly exhibited anxiety');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1898',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1902',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1951',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1975',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1977',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2034',null,'PN_0005','61967-6',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with depression or bipolar/manic depression ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1913',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1915',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1948',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2035',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1915',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2021',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1874',null,'PN_0017','61949-4',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1890',null,'PN_0017','61949-4',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1911',null,'PN_0017','61949-4',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1912',null,'PN_0017','61949-4',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1904',null,'PN_0017','61949-4',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder; or the patient repeatedly exhibited anxiety');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2007',null,'PN_0017','61949-4',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder; or the patient repeatedly exhibited anxiety');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1881',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1885',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1970',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2046',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2049',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1888',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1934',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1981',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1915',null,'PN_0007','75417-6',null,null,2,'EC','PR','N',null,'The patient''s interest in social interaction decreased in adulthood');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1936',null,'PN_0017','61949-4',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder; or the patient repeatedly exhibited anxiety');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1879',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1936',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2004',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2007',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1928',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2020',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2026',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1948',null,'PN_0006','61998-1',null,null,1,'EC','PR','N',null,'The patient never experienced any of these symptoms neither insomnia ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1890',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1891',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1892',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1911',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1916',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1974',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2034',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2035',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2020',null,'PN_0007','75417-6',null,null,3,'EC','PR','N',null,'The patient''s interest in social interaction increased in adulthood');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2026',null,'PN_0007','75417-6',null,null,2,'EC','PR','N',null,'The patient''s interest in social interaction decreased in adulthood');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2003',null,'PN_0017','61949-4',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1888',null,'PN_0017','61949-4',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder; or the patient repeatedly exhibited anxiety');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1893',null,'PN_0017','61949-4',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder; or the patient repeatedly exhibited anxiety');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1874',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2039',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2051',null,'PN_0012','75416-8',null,null,0,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1972',null,'PN_0005','61967-6',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with depression or bipolar/manic depression ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1869',null,'PN_0005','61967-6',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with depression neither bipolar/manic depression');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1972',null,'PN_0006','61998-1',null,null,1,'EC','PR','N',null,'The patient never experienced any of these symptoms neither insomnia ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1934',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1935',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2023',null,'PN_0006','61998-1',null,null,5,'EC','PR','N',null,'The patient experienced insomnia in adolescence/adulthood ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1889',null,'PN_0007','75417-6',null,null,3,'EC','PR','N',null,'The patient''s interest in social interaction increased in adulthood');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1914',null,'PN_0017','61949-4',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1978',null,'PN_0017','61949-4',null,null,1,'EC','PR','N',null,'The patient has never been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder neither exhibited anxiety ');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1917',null,'PN_0017','61949-4',null,null,5,'EC','PR','N',null,'The patient has been diagnosed with anxiety disorder or panic attacks or obsessive compulsive disorder; or the patient repeatedly exhibited anxiety');
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2016',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1909',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1875',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1959',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2050',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2014',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1965',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2005',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1926',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1960',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1968',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1910',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1882',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2054',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1976',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1993',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1953',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1992',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1883',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1938',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1918',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1944',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2019',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1907',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1876',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2053',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2044',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1980',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1994',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1900',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1989',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2025',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1880',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1877',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1906',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1961',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2032',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1962',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2040',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1894',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2038',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1952',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1930',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1946',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1942',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2001',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1983',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1995',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2009',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1973',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1984',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2015',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2011',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1987',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1950',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2008',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1929',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2048',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1897',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1901',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2041',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1982',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1873',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1870',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1884',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1999',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1943',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2012',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2013',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1969',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2056',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1905',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1985',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2006',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2045',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1979',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2057',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1899',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1991',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1941',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2031',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2028',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2055',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2027',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1927',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1986',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1925',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1967',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1871',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1945',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1964',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2010',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1887',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1872',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1896',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1963',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1878',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1923',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1940',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1868',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1908',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2052',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1958',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1933',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2043',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2018',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2022',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1919',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2000',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1867',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1932',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1966',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1924',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2042',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1996',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1990',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1937',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1971',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2047',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1920',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('1939',null,null,null,null,null,null,'EC','PR','N',null,null);
Insert into PCORI_CDMV2.PRO_CM (PATID,ENCOUNTERID,CM_ITEM,CM_LOINC,CM_DATE,CM_TIME,CM_RESPONSE,CM_METHOD,CM_MODE,CM_CAT,RAW_CM_CODE,RAW_CM_RESPONSE) values ('2036',null,null,null,null,null,null,'EC','PR','N',null,null);
--------------------------------------------------------
