DROP TABLE "I2B2DEMODATA"."SAMPLE_CATEGORIES";

 CREATE TABLE "I2B2DEMODATA"."SAMPLE_CATEGORIES" 
   (	
  "PATIENT_NUM" VARCHAR2(2000 BYTE) NULL,    
  "SAMPLE_ID" VARCHAR2(2000 BYTE) NOT NULL, 
  "SAMPLE_NAME" VARCHAR2(2000 BYTE),
	"COLLECTION_DESC" VARCHAR2(2000 BYTE), 
	"SAMPLE_TYPE" VARCHAR2(2000 BYTE), 
	"ALIQUOT_NO" VARCHAR2(2000 BYTE), 
	"ALIQUOT_VOLUME" VARCHAR2(2000 BYTE), --In Grid
  "INSTRUMENT" VARCHAR2(2000 BYTE),
  "SAMPLE_PROTOCOL" VARCHAR2(2000 BYTE),  
  "INVENTORY_STATUS" VARCHAR2(2000 BYTE),
  "POSITION" VARCHAR2(2000 BYTE), --In Grid
  "TOTAL_MICROGRAMS" VARCHAR2(2000 BYTE), --In Grid
  "A260_A280" VARCHAR2(2000 BYTE),
  "A260_A230" VARCHAR2(2000 BYTE),
  "A260_NG_UL" VARCHAR2(2000 BYTE),
  "28S_18S" VARCHAR2(2000 BYTE),
  "RIN" VARCHAR2(2000 BYTE),
  "BIOA_NG_UL" VARCHAR2(2000 BYTE),
  "DSDNA_NG_UL" VARCHAR2(2000 BYTE),
  "PROTOCOL_TITLE" VARCHAR2(2000 BYTE),
  "GENDER" VARCHAR2(2000 BYTE),
  "MINUTES_SINCE_CALORIES" VARCHAR2(2000 BYTE),
  "PEDIGREE_NAME" VARCHAR2(2000 BYTE),
  "PROBAND_STATUS" VARCHAR2(2000 BYTE),
  "ANALYSIS" VARCHAR2(2000 BYTE),
  "PLATFORM" VARCHAR2(2000 BYTE),
  "ASSAY" VARCHAR2(2000 BYTE),
  "FACILITY" VARCHAR2(2000 BYTE),
  "STUDY_ID" VARCHAR2(2000 BYTE),
  "CONTACT" VARCHAR2(2000 BYTE)
   );

ALTER TABLE "I2B2DEMODATA"."SAMPLE_CATEGORIES"  ADD (CONSTRAINT SAMPLE_ID_PK PRIMARY KEY (SAMPLE_ID));   
--ALTER TABLE "I2B2DEMODATA"."SAMPLE_CATEGORIES" MODIFY (PATIENT_NUM NULL);
grant select  on deapp.seq_assay_id to tm_lz;

--Couldn't get this to work.
--CREATE synonym seq_assay_id FOR "deapp".seq_assay_id;
--
--CREATE OR REPLACE TRIGGER "I2B2DEMODATA".sample_id_insert_trigger 
--BEFORE INSERT ON "I2B2DEMODATA"."SAMPLE_CATEGORIES" 
--FOR EACH ROW
--
--BEGIN
--  SELECT seq_assay_id.NEXTVAL
--  INTO   :new.sample_id
--  FROM   dual;
--END;
--/


TRUNCATE TABLE "TM_LZ"."AUTISM_SUBJECT";

--Protocol ID	Protocol ID.Protocol title	Individual name	Individual alias	Gender	Pedigree name	Proband status	Individual notes
 CREATE TABLE "TM_LZ"."AUTISM_SUBJECT"
 (
  "PROTOCOL_ID" VARCHAR2(2000 BYTE),
  "PROTOCOL_TITLE" VARCHAR2(2000 BYTE),
  "INDIVIDUAL_NAME" VARCHAR2(2000 BYTE),
  "INDIVIDUAL_ALIAS" VARCHAR2(2000 BYTE),
  "GENDER" VARCHAR2(2000 BYTE),
  "PEDIGREE_NAME" VARCHAR2(2000 BYTE),
  "PROBAND_STATUS" VARCHAR2(2000 BYTE),
  "INDIVIDUAL_NOTES" VARCHAR2(2000 BYTE)
 );
 
 TRUNCATE TABLE "TM_LZ"."AUTISM_ALIQUOT";
 
 --Individual name	Collection date	Collection time (24:00)	Extraction date	Sample Name	Sample type	Aliquot no.	Volume	Total micrograms	A260/A280	A260/A230	ng/ul (A260)	28s/18s	RIN	ng/ul (BioA)	ng/ul (dsDNA)	Inventory status	Sample notes	Container Name	Position Sample notes	Parent Sample Name
  CREATE TABLE "TM_LZ"."AUTISM_ALIQUOT"
 (
  "INDIVIDUAL_NAME" VARCHAR2(2000 BYTE),
  "COLLECTION_DATE" VARCHAR2(2000 BYTE),
  "COLLECTION_TIME" VARCHAR2(2000 BYTE),
  "EXTRACTION_DATE" VARCHAR2(2000 BYTE),
  "SAMPLE_NAME" VARCHAR2(2000 BYTE),
  "SAMPLE_TYPE" VARCHAR2(2000 BYTE),
  "ALIQUOT_NUMBER" VARCHAR2(2000 BYTE),
  "ALIQUOT_VOLUME" VARCHAR2(2000 BYTE),
  "ALIQUOT_WEIGHT" VARCHAR2(2000 BYTE),
  "A260_A280" VARCHAR2(2000 BYTE),
  "A260_A230" VARCHAR2(2000 BYTE),
  "A260_NG_UL" VARCHAR2(2000 BYTE),
  "28S_18S" VARCHAR2(2000 BYTE),
  "RIN" VARCHAR2(2000 BYTE),
  "BIOA_NG_UL" VARCHAR2(2000 BYTE),
  "DSDNA_NG_UL" VARCHAR2(2000 BYTE),
  "INVENTORY_STATUS" VARCHAR2(2000 BYTE),
  "SAMPLE_NOTES" VARCHAR2(2000 BYTE),
  "CONTAINER_NAME" VARCHAR2(2000 BYTE),
  "POSITION" VARCHAR2(2000 BYTE),
  "PARENT_SAMPLE_NAME" VARCHAR2(2000 BYTE)
 );
 
--Individual name	Sample Name	Analysis History Table.Analysis	Analysis History Table.Platform	Analysis History Table.Assay	Analysis History Table.Date	Analysis History Table.Comments	Analysis History Table.Facility 
CREATE TABLE "TM_LZ"."AUTISM_ANALYSIS"
(
  "INDIVIDUAL_NAME" VARCHAR2(2000 BYTE),
  "SAMPLE_NAME" VARCHAR2(2000 BYTE),
  "ANALYSIS" VARCHAR2(2000 BYTE),
  "PLATFORM" VARCHAR2(2000 BYTE),
  "ASSAY" VARCHAR2(2000 BYTE),
  "DATE" VARCHAR2(2000 BYTE),
  "COMMENTS" VARCHAR2(2000 BYTE),
  "FACILITY" VARCHAR2(2000 BYTE)
);

--Some of the header records were imported, remove them here.
DELETE FROM TM_LZ.AUTISM_ANALYSIS WHERE ANALYSIS IS NULL;

--Individual name	
--Sample Name	
--Collection description	
--Sample type	
--Aliquot no.	
--Collection volume (ml)	
--Collection no.	
--Hours:minutes since last caloric intake (00:00)	
--Collection date	
--Collection time (24:00)	
--Freeze date	
--Freeze time	
--Extraction date	
--Thaw start time (24:00)	
--START time (24:00)	
--END time (24:00)	
--Instrument	
--Sample protocol	
--Collection notes	
--Sample notes	
--Inventory status	
--Container Name	
--Position	
--Parent Sample Name
CREATE TABLE "TM_LZ"."AUTISM_COLLECTION"
(
  "INDIVIDUAL_NAME" VARCHAR2(2000 BYTE),
  "SAMPLE_NAME" VARCHAR2(2000 BYTE),
  "COLLECTION_DESCRIPTION" VARCHAR2(2000 BYTE),
  "SAMPLE_TYPE" VARCHAR2(2000 BYTE),
  "ALIQUOT_NUMBER" VARCHAR2(2000 BYTE),
  "ALIQUOT_VOLUME" VARCHAR2(2000 BYTE),
  "COLLECTION_NUMBER" VARCHAR2(2000 BYTE),
  "MINUTES_SINCE_CALORIES" VARCHAR2(2000 BYTE),
  "COLLECTION_DATE" VARCHAR2(2000 BYTE),
  "COLLECTION_TIME" VARCHAR2(2000 BYTE),
  "FREEZE_DATE" VARCHAR2(2000 BYTE),
  "FREEZE_TIME" VARCHAR2(2000 BYTE),
  "EXTRACTION_DATE" VARCHAR2(2000 BYTE),
  "THAW_START_TIME" VARCHAR2(2000 BYTE),
  "START_TIME" VARCHAR2(2000 BYTE),
  "END_TIME" VARCHAR2(2000 BYTE),
  "INSTRUMENT" VARCHAR2(2000 BYTE),
  "SAMPLE_PROTOCOL" VARCHAR2(2000 BYTE),
  "COLLECTION_NOTES" VARCHAR2(2000 BYTE),
  "SAMPLE_NOTES" VARCHAR2(2000 BYTE),
  "INVENTORY_STATUS" VARCHAR2(2000 BYTE),
  "CONTAINER_NAME" VARCHAR2(2000 BYTE),
  "POSITION" VARCHAR2(2000 BYTE),
  "PARENT_SAMPLE_NAME" VARCHAR2(2000 BYTE)
);

TRUNCATE TABLE TM_LZ.SSC_LINKAGE;

CREATE TABLE "TM_LZ"."SSC_LINKAGE"
(
  "INTERNAL_FAMILY_ID"  VARCHAR2(2000 BYTE),
  "PRIMARY_ID"          VARCHAR2(2000 BYTE),
  "SECONDARY_ID"        VARCHAR2(2000 BYTE),
  "BCH_FAMILY_ID"       VARCHAR2(2000 BYTE),
  "ID"                  VARCHAR2(2000 BYTE),
  "SEX"                 VARCHAR2(2000 BYTE),
  "DOB"                 VARCHAR2(2000 BYTE)
);

--Create one big table with all the sample level sample data.
CREATE TABLE "TM_LZ"."ALL_SAMPLE_DATA"
(
  "INDIVIDUAL_NAME" VARCHAR2(2000 BYTE),
  "SAMPLE_NAME" VARCHAR2(2000 BYTE),
  "COLLECTION_DESCRIPTION" VARCHAR2(2000 BYTE),
  "SAMPLE_TYPE" VARCHAR2(2000 BYTE),
  "ALIQUOT_NUMBER" VARCHAR2(2000 BYTE),
  "ALIQUOT_VOLUME" VARCHAR2(2000 BYTE),
  "COLLECTION_NUMBER" VARCHAR2(2000 BYTE),
  "MINUTES_SINCE_CALORIES" VARCHAR2(2000 BYTE),
  "COLLECTION_DATE" VARCHAR2(2000 BYTE),
  "COLLECTION_TIME" VARCHAR2(2000 BYTE),
  "FREEZE_DATE" VARCHAR2(2000 BYTE),
  "FREEZE_TIME" VARCHAR2(2000 BYTE),
  "EXTRACTION_DATE" VARCHAR2(2000 BYTE),
  "THAW_START_TIME" VARCHAR2(2000 BYTE),
  "START_TIME" VARCHAR2(2000 BYTE),
  "END_TIME" VARCHAR2(2000 BYTE),
  "INSTRUMENT" VARCHAR2(2000 BYTE),
  "SAMPLE_PROTOCOL" VARCHAR2(2000 BYTE),
  "COLLECTION_NOTES" VARCHAR2(2000 BYTE),
  "SAMPLE_NOTES" VARCHAR2(2000 BYTE),
  "INVENTORY_STATUS" VARCHAR2(2000 BYTE),
  "CONTAINER_NAME" VARCHAR2(2000 BYTE),
  "POSITION" VARCHAR2(2000 BYTE),
  "PARENT_SAMPLE_NAME" VARCHAR2(2000 BYTE),
  "INDIVIDUAL_NAME_ALIQ" VARCHAR2(2000 BYTE),
  "COLLECTION_DATE_ALIQ" VARCHAR2(2000 BYTE),
  "COLLECTION_TIME_ALIQ" VARCHAR2(2000 BYTE),
  "EXTRACTION_DATE_ALIQ" VARCHAR2(2000 BYTE),
  "SAMPLE_NAME_ALIQ" VARCHAR2(2000 BYTE),
  "SAMPLE_TYPE_ALIQ" VARCHAR2(2000 BYTE),
  "ALIQUOT_NUMBER_ALIQ" VARCHAR2(2000 BYTE),
  "ALIQUOT_VOLUME_ALIQ" VARCHAR2(2000 BYTE),
  "ALIQUOT_WEIGHT_ALIQ" VARCHAR2(2000 BYTE),
  "A260_A280_ALIQ" VARCHAR2(2000 BYTE),
  "A260_A230_ALIQ" VARCHAR2(2000 BYTE),
  "A260_NG_UL_ALIQ" VARCHAR2(2000 BYTE),
  "28S_18S_ALIQ" VARCHAR2(2000 BYTE),
  "RIN_ALIQ" VARCHAR2(2000 BYTE),
  "BIOA_NG_UL_ALIQ" VARCHAR2(2000 BYTE),
  "DSDNA_NG_UL_ALIQ" VARCHAR2(2000 BYTE),
  "INVENTORY_STATUS_ALIQ" VARCHAR2(2000 BYTE),
  "SAMPLE_NOTES_ALIQ" VARCHAR2(2000 BYTE),
  "CONTAINER_NAME_ALIQ" VARCHAR2(2000 BYTE),
  "POSITION_ALIQ" VARCHAR2(2000 BYTE),
  "PARENT_SAMPLE_NAME_ALIQ" VARCHAR2(2000 BYTE),
  "INDIVIDUAL_NAME_ANA" VARCHAR2(2000 BYTE),
  "SAMPLE_NAME_ANA" VARCHAR2(2000 BYTE),
  "ANALYSIS_ANA" VARCHAR2(2000 BYTE),
  "PLATFORM_ANA" VARCHAR2(2000 BYTE),
  "ASSAY_ANA" VARCHAR2(2000 BYTE),
  "DATE_ANA" VARCHAR2(2000 BYTE),
  "COMMENTS_ANA" VARCHAR2(2000 BYTE),
  "FACILITY_ANA" VARCHAR2(2000 BYTE) 
);

--0
--SELECT SAMPLE_TYPE,SAMPLE_TYPE_ALIQ FROM ALL_SAMPLE_DATA WHERE SAMPLE_TYPE IS NOT NULL AND SAMPLE_TYPE_ALIQ IS NOT NULL AND SAMPLE_TYPE != SAMPLE_TYPE_ALIQ;
--0
--SELECT SAMPLE_TYPE,SAMPLE_TYPE_ALIQ FROM ALL_SAMPLE_DATA WHERE SAMPLE_TYPE != SAMPLE_TYPE_ALIQ;

--0
--SELECT INVENTORY_STATUS,INVENTORY_STATUS_ALIQ FROM ALL_SAMPLE_DATA WHERE INVENTORY_STATUS IS NOT NULL AND INVENTORY_STATUS_ALIQ IS NOT NULL;

--0
--SELECT ALIQUOT_NUMBER,ALIQUOT_NUMBER_ALIQ FROM ALL_SAMPLE_DATA WHERE ALIQUOT_NUMBER IS NOT NULL AND ALIQUOT_NUMBER_ALIQ IS NOT NULL AND ALIQUOT_NUMBER != ALIQUOT_NUMBER_ALIQ;
--0
--SELECT ALIQUOT_NUMBER,ALIQUOT_NUMBER_ALIQ FROM ALL_SAMPLE_DATA WHERE ALIQUOT_NUMBER != ALIQUOT_NUMBER_ALIQ;

--0
--SELECT ALIQUOT_VOLUME,ALIQUOT_VOLUME_ALIQ FROM ALL_SAMPLE_DATA WHERE ALIQUOT_VOLUME IS NOT NULL AND ALIQUOT_VOLUME_ALIQ IS NOT NULL AND ALIQUOT_VOLUME != ALIQUOT_VOLUME_ALIQ;

INSERT INTO "TM_LZ"."ALL_SAMPLE_DATA"

SELECT aut_col.*, aut_aliq.*, aut_ana.*
FROM  TM_LZ.AUTISM_COLLECTION aut_col
INNER JOIN TM_LZ.AUTISM_ALIQUOT aut_aliq ON aut_aliq.INDIVIDUAL_NAME = aut_col.INDIVIDUAL_NAME AND aut_col.SAMPLE_NAME = aut_aliq.SAMPLE_NAME
INNER JOIN TM_LZ.AUTISM_ANALYSIS aut_ana ON aut_ana.INDIVIDUAL_NAME = aut_col.INDIVIDUAL_NAME AND aut_aliq.SAMPLE_NAME = aut_ana.SAMPLE_NAME

UNION ALL

SELECT aut_col.*, aut_aliq.*, aut_ana.*
FROM  TM_LZ.AUTISM_COLLECTION aut_col
INNER JOIN TM_LZ.AUTISM_ALIQUOT aut_aliq ON aut_aliq.INDIVIDUAL_NAME = aut_col.INDIVIDUAL_NAME AND aut_col.SAMPLE_NAME = aut_aliq.SAMPLE_NAME
LEFT JOIN TM_LZ.AUTISM_ANALYSIS aut_ana ON aut_ana.INDIVIDUAL_NAME = aut_col.INDIVIDUAL_NAME AND aut_aliq.SAMPLE_NAME = aut_ana.SAMPLE_NAME
WHERE aut_ana.INDIVIDUAL_NAME IS NULL

UNION ALL

SELECT aut_col.*, aut_aliq.*, aut_ana.*
FROM  TM_LZ.AUTISM_COLLECTION aut_col
INNER JOIN TM_LZ.AUTISM_ANALYSIS aut_ana ON aut_ana.INDIVIDUAL_NAME = aut_col.INDIVIDUAL_NAME AND aut_col.SAMPLE_NAME = aut_ana.SAMPLE_NAME
LEFT JOIN TM_LZ.AUTISM_ALIQUOT aut_aliq ON aut_aliq.INDIVIDUAL_NAME = aut_col.INDIVIDUAL_NAME AND aut_col.SAMPLE_NAME = aut_aliq.SAMPLE_NAME
WHERE aut_aliq.INDIVIDUAL_NAME IS NULL

UNION ALL

SELECT aut_col.*, aut_aliq.*, aut_ana.*
FROM  TM_LZ.AUTISM_ALIQUOT aut_aliq
INNER JOIN TM_LZ.AUTISM_ANALYSIS aut_ana ON aut_ana.INDIVIDUAL_NAME = aut_aliq.INDIVIDUAL_NAME AND aut_aliq.SAMPLE_NAME = aut_ana.SAMPLE_NAME
LEFT JOIN TM_LZ.AUTISM_COLLECTION aut_col ON aut_aliq.INDIVIDUAL_NAME = aut_col.INDIVIDUAL_NAME AND aut_col.SAMPLE_NAME = aut_aliq.SAMPLE_NAME
WHERE aut_col.INDIVIDUAL_NAME IS NULL

UNION ALL

SELECT aut_col.*, aut_aliq.*, aut_ana.*
FROM  TM_LZ.AUTISM_ALIQUOT aut_aliq
LEFT JOIN TM_LZ.AUTISM_ANALYSIS aut_ana ON aut_ana.INDIVIDUAL_NAME = aut_aliq.INDIVIDUAL_NAME AND aut_aliq.SAMPLE_NAME = aut_ana.SAMPLE_NAME
LEFT JOIN TM_LZ.AUTISM_COLLECTION aut_col ON aut_aliq.INDIVIDUAL_NAME = aut_col.INDIVIDUAL_NAME AND aut_col.SAMPLE_NAME = aut_aliq.SAMPLE_NAME
WHERE aut_col.INDIVIDUAL_NAME IS NULL AND aut_ana.INDIVIDUAL_NAME IS NULL

UNION ALL

SELECT aut_col.*, aut_aliq.*, aut_ana.*
FROM  TM_LZ.AUTISM_COLLECTION aut_col
LEFT JOIN TM_LZ.AUTISM_ANALYSIS aut_ana ON aut_ana.INDIVIDUAL_NAME = aut_col.INDIVIDUAL_NAME AND aut_col.SAMPLE_NAME = aut_ana.SAMPLE_NAME
LEFT JOIN TM_LZ.AUTISM_ALIQUOT aut_aliq ON aut_aliq.INDIVIDUAL_NAME = aut_col.INDIVIDUAL_NAME AND aut_col.SAMPLE_NAME = aut_aliq.SAMPLE_NAME
WHERE aut_aliq.INDIVIDUAL_NAME IS NULL AND aut_ana.INDIVIDUAL_NAME IS NULL

UNION ALL

SELECT aut_col.*, aut_aliq.*, aut_ana.*
FROM  TM_LZ.AUTISM_ANALYSIS aut_ana
LEFT JOIN TM_LZ.AUTISM_COLLECTION aut_col ON aut_ana.INDIVIDUAL_NAME = aut_col.INDIVIDUAL_NAME AND aut_col.SAMPLE_NAME = aut_ana.SAMPLE_NAME
LEFT JOIN TM_LZ.AUTISM_ALIQUOT aut_aliq ON aut_aliq.INDIVIDUAL_NAME = aut_ana.INDIVIDUAL_NAME AND aut_ana.SAMPLE_NAME = aut_aliq.SAMPLE_NAME
WHERE aut_aliq.INDIVIDUAL_NAME IS NULL AND aut_col.INDIVIDUAL_NAME IS NULL;

--TRUNCATE TABLE "I2B2DEMODATA"."SAMPLE_CATEGORIES";

--We'll load the SAMPLE_CATEGORIES table first and then backfill DE_SUBJECT_SAMPLE_MAPPING. We'll use the assay_id trigger for DE_SUBJECT_SAMPLE_MAPPING.
INSERT INTO "I2B2DEMODATA"."SAMPLE_CATEGORIES" 

(
  PATIENT_NUM,
  SAMPLE_ID,
  SAMPLE_NAME,
  COLLECTION_DESC,
  SAMPLE_TYPE,
  ALIQUOT_NO,
  ALIQUOT_VOLUME,
  INSTRUMENT,
  SAMPLE_PROTOCOL,
  INVENTORY_STATUS,
  POSITION,
  TOTAL_MICROGRAMS,
  A260_A280,
  A260_A230,
  A260_NG_UL,
  "28S_18S",
  RIN,
  BIOA_NG_UL,
  DSDNA_NG_UL,
  PROTOCOL_TITLE,
  GENDER,
  MINUTES_SINCE_CALORIES,
  PEDIGREE_NAME,
  PROBAND_STATUS,
  ANALYSIS,
  PLATFORM,
  ASSAY,
  FACILITY,
  STUDY_ID,
  CONTACT
)
SELECT  subQuery.PATIENT_NUM,
        deapp.seq_assay_id.NEXTVAL,
        subQuery.SAMPLE_NAME,
        subQuery.collection_description,
        subQuery.sample_type_aliq,
        subQuery.aliquot_number_aliq,
        subQuery.aliquot_volume_aliq,
        subQuery.instrument,
        subQuery.sample_protocol,
        subQuery.inventory_status,
        subQuery.position,
        null,
        subQuery.a260_a280_aliq,
        subQuery.a260_a230_aliq,
        subQuery.a260_ng_ul_aliq,
        subQuery."28S_18S_ALIQ",
        subQuery.rin_aliq,
        subQuery.bioa_ng_ul_aliq,
        subQuery.dsdna_ng_ul_aliq,
        subQuery.protocol_title,
        subQuery.gender,
        subQuery.minutes_since_calories,
        subQuery.pedigree_name,
        subQuery.proband_status,
        subQuery.analysis_ana,
        subQuery.platform_ana,
        subQuery.assay_ana,
        subQuery.facility_ana,
        'GENOPHENO',
        null
FROM (SELECT  PD.PATIENT_NUM,
        ALL_SAMPLE.SAMPLE_NAME,
        ALL_SAMPLE.collection_description,
        ALL_SAMPLE.SAMPLE_TYPE_ALIQ, --Never differ
        ALL_SAMPLE.ALIQUOT_NUMBER_ALIQ, --Never differ
        ALL_SAMPLE.ALIQUOT_VOLUME_ALIQ,
        ALL_SAMPLE.instrument, --Only 1 field
        ALL_SAMPLE.sample_protocol, --Only 1 field
        COALESCE(ALL_SAMPLE.INVENTORY_STATUS,ALL_SAMPLE.INVENTORY_STATUS_ALIQ) inventory_status,  
        ALL_SAMPLE.position, --Only 1 field
        null,
        ALL_SAMPLE.a260_a280_aliq,
        ALL_SAMPLE.a260_a230_aliq,
        ALL_SAMPLE.a260_ng_ul_aliq,
        ALL_SAMPLE."28S_18S_ALIQ",
        ALL_SAMPLE.rin_aliq,
        ALL_SAMPLE.bioa_ng_ul_aliq,
        ALL_SAMPLE.dsdna_ng_ul_aliq,
        aut_sub.protocol_title,
        aut_sub.gender,
        ALL_SAMPLE.minutes_since_calories,
        aut_sub.pedigree_name,
        aut_sub.proband_status,
        ALL_SAMPLE.analysis_ana,
        ALL_SAMPLE.platform_ana,
        ALL_SAMPLE.assay_ana, 
        ALL_SAMPLE.facility_ana,
        'GENOPHENO'
FROM i2b2DemoData.PATIENT_DIMENSION PD
INNER JOIN TM_LZ.SSC_LINKAGE SLINK ON SLINK.ID =  SUBSTR(PD.SOURCESYSTEM_CD,11)
LEFT JOIN TM_LZ.ALL_SAMPLE_DATA ALL_SAMPLE ON SUBSTR(ALL_SAMPLE.INDIVIDUAL_NAME,5) = SLINK.PRIMARY_ID
LEFT JOIN TM_LZ.AUTISM_SUBJECT aut_sub ON SUBSTR(aut_sub.INDIVIDUAL_NAME,5) = SLINK.PRIMARY_ID
WHERE PD.SOURCESYSTEM_CD LIKE '%GENOPHENO%') subQuery ;

--Now insert into DE_SUBJECT_SAMPLE_MAPPING.
INSERT INTO DEAPP.DE_SUBJECT_SAMPLE_MAPPING (PATIENT_ID, SUBJECT_ID, TRIAL_NAME, SAMPLE_ID, SAMPLE_TYPE)
SELECT  PD.PATIENT_NUM,
        REGEXP_SUBSTR(SOURCESYSTEM_CD,'[^:]+',1,2),
        'GENOPHENO',
        SC.SAMPLE_ID,
        'BIOBANK'
FROM I2B2DEMODATA.PATIENT_DIMENSION PD
INNER JOIN "I2B2DEMODATA"."SAMPLE_CATEGORIES" SC ON SC.PATIENT_NUM = PD.PATIENT_NUM;

--DELETE FROM DEAPP.DE_SUBJECT_SAMPLE_MAPPING WHERE TRIAL_NAME = 'GENOPHENO' AND SAMPLE_TYPE = 'BIOBANK';

--Fill in the ASSAY_ID column.
UPDATE DEAPP.DE_SUBJECT_SAMPLE_MAPPING SET ASSAY_ID = SAMPLE_ID WHERE SAMPLE_TYPE = 'BIOBANK';

--Load the samples without any patient data. These patients have entries in the 4 tables that we can join on.
INSERT INTO "I2B2DEMODATA"."SAMPLE_CATEGORIES" 

(
  PATIENT_NUM,
  SAMPLE_ID,
  SAMPLE_NAME,
  COLLECTION_DESC,
  SAMPLE_TYPE,
  ALIQUOT_NO,
  ALIQUOT_VOLUME,
  INSTRUMENT,
  SAMPLE_PROTOCOL,
  INVENTORY_STATUS,
  POSITION,
  TOTAL_MICROGRAMS,
  A260_A280,
  A260_A230,
  A260_NG_UL,
  "28S_18S",
  RIN,
  BIOA_NG_UL,
  DSDNA_NG_UL,
  PROTOCOL_TITLE,
  GENDER,
  MINUTES_SINCE_CALORIES,
  PEDIGREE_NAME,
  PROBAND_STATUS,
  ANALYSIS,
  PLATFORM,
  ASSAY,
  FACILITY,
  STUDY_ID,
  CONTACT
)
SELECT  null,
        deapp.seq_assay_id.NEXTVAL,
        subQuery.SAMPLE_NAME,
        subQuery.collection_description,
        subQuery.sample_type_aliq,
        subQuery.aliquot_number_aliq,
        subQuery.aliquot_volume_aliq,
        subQuery.instrument,
        subQuery.sample_protocol,
        subQuery.inventory_status,
        subQuery.position,
        null,
        subQuery.a260_a280_aliq,
        subQuery.a260_a230_aliq,
        subQuery.a260_ng_ul_aliq,
        subQuery."28S_18S_ALIQ",
        subQuery.rin_aliq,
        subQuery.bioa_ng_ul_aliq,
        subQuery.dsdna_ng_ul_aliq,
        subQuery.protocol_title,
        subQuery.gender,
        subQuery.minutes_since_calories,
        subQuery.pedigree_name,
        subQuery.proband_status,
        subQuery.analysis_ana,
        subQuery.platform_ana,
        subQuery.assay_ana,
        subQuery.facility_ana,
        'GENOPHENO',
        null
FROM (SELECT  null,
        ALL_SAMPLE.SAMPLE_NAME,
        ALL_SAMPLE.collection_description,
        ALL_SAMPLE.SAMPLE_TYPE_ALIQ, --Never differ
        ALL_SAMPLE.ALIQUOT_NUMBER_ALIQ, --Never differ
        ALL_SAMPLE.ALIQUOT_VOLUME_ALIQ,
        ALL_SAMPLE.instrument, --Only 1 field
        ALL_SAMPLE.sample_protocol, --Only 1 field
        COALESCE(ALL_SAMPLE.INVENTORY_STATUS,ALL_SAMPLE.INVENTORY_STATUS_ALIQ) inventory_status,  
        ALL_SAMPLE.position, --Only 1 field
        null,
        ALL_SAMPLE.a260_a280_aliq,
        ALL_SAMPLE.a260_a230_aliq,
        ALL_SAMPLE.a260_ng_ul_aliq,
        ALL_SAMPLE."28S_18S_ALIQ",
        ALL_SAMPLE.rin_aliq,
        ALL_SAMPLE.bioa_ng_ul_aliq,
        ALL_SAMPLE.dsdna_ng_ul_aliq,
        aut_sub.protocol_title,
        aut_sub.gender,
        ALL_SAMPLE.minutes_since_calories,
        aut_sub.pedigree_name,
        aut_sub.proband_status,
        ALL_SAMPLE.analysis_ana,
        ALL_SAMPLE.platform_ana,
        ALL_SAMPLE.assay_ana, 
        ALL_SAMPLE.facility_ana,
        'GENOPHENO'
FROM TM_LZ.AUTISM_SUBJECT aut_sub
LEFT JOIN TM_LZ.ALL_SAMPLE_DATA ALL_SAMPLE ON ALL_SAMPLE.INDIVIDUAL_NAME = aut_sub.INDIVIDUAL_NAME
WHERE SUBSTR(aut_sub.INDIVIDUAL_NAME,5) NOT IN (SELECT PRIMARY_ID FROM TM_LZ.SSC_LINKAGE)) subQuery ;

UPDATE i2b2DemoData.SAMPLE_CATEGORIES SET PROTOCOL_TITLE = 'Tuberous Sclerosis Complex' WHERE PROTOCOL_TITLE = 'TUBEROUS SCLEROSIS COMPLEX';
UPDATE i2b2DemoData.SAMPLE_CATEGORIES SET PROTOCOL_TITLE = 'Seaside Therapeutics/R-baclofen' WHERE PROTOCOL_TITLE = 'Pharmacological Mediation of Plasticity (Seaside Therapeutics/R-baclofen)';
UPDATE i2b2DemoData.SAMPLE_CATEGORIES SET PROTOCOL_TITLE = 'Autism Consortium' WHERE PROTOCOL_TITLE = 'Phenotypic and Genetic Risk Factors in Autism Spectrum Disorders (AUTISM CONSORTIUM)';
UPDATE i2b2DemoData.SAMPLE_CATEGORIES SET PROTOCOL_TITLE = 'Pre Autism Consortium' WHERE PROTOCOL_TITLE = 'Phenotypic and Genetic Risk Factors in Autism Spectrum Disorders';
UPDATE i2b2DemoData.SAMPLE_CATEGORIES SET PROTOCOL_TITLE = 'Autism Linguistics' WHERE PROTOCOL_TITLE = 'AUTISM LINGUISTICS';
UPDATE i2b2DemoData.SAMPLE_CATEGORIES SET PROTOCOL_TITLE = 'All Comers' WHERE PROTOCOL_TITLE = 'Genetic Contributions to Autism Spectrum Disorders (All Comers)';
UPDATE i2b2DemoData.SAMPLE_CATEGORIES SET PROTOCOL_TITLE = 'Rett Syndrome' WHERE PROTOCOL_TITLE = 'Pharmacological Teatment of Rett syndrome by Stimulation of synaptic Maturation with IGF-1: Phase 1';
UPDATE i2b2DemoData.SAMPLE_CATEGORIES SET PROTOCOL_TITLE = 'SFARI Simplex Collection' WHERE PROTOCOL_TITLE = 'Phenotypic and Genetic Risk Factors in Autism Spectrum Disorders (SIMONS SIMPLEX)';

UPDATE I2B2DEMODATA.SAMPLE_CATEGORIES SET CONTACT = 'contact@mit.edu' WHERE FACILITY = 'Broad Institute';
UPDATE I2B2DEMODATA.SAMPLE_CATEGORIES SET CONTACT = 'contact@harvard.edu' WHERE FACILITY = 'Kunkel Lab';
UPDATE I2B2DEMODATA.SAMPLE_CATEGORIES SET CONTACT = 'Tram.Tran@childrens.harvard.edu' WHERE CONTACT IS NULL;

UPDATE I2B2DEMODATA.SAMPLE_CATEGORIES SET STUDY_ID = 'Geno-Pheno';


SELECT * FROM "TM_LZ"."ALL_SAMPLE_DATA";

