----------------------------------------------------
--COLUMN MODIFICATIONS
----------------------------------------------------



----------------------------------------------------
--MODIFIER_DIMENSION
----------------------------------------------------
SELECT * FROM TM_LZ.MODIFIER_DIMENSION_I2B2_MTM;
SELECT * FROM I2B2DEMODATA.MODIFIER_DIMENSION;

INSERT INTO I2B2DEMODATA.MODIFIER_DIMENSION
(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
SELECT  MODIFIER_PATH,
        MODIFIER_CD,
        NAME_CHAR,
        TO_LOB(MODIFIER_BLOB),
        TO_TIMESTAMP(UPDATE_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
        TO_TIMESTAMP(DOWNLOAD_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
        TO_TIMESTAMP(IMPORT_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
        SOURCESYSTEM_CD,
        UPLOAD_ID
FROM    TM_LZ.MODIFIER_DIMENSION_I2B2_MTM;


SELECT  MODIFIER_PATH,
        MODIFIER_CD,
        NAME_CHAR,
        MODIFIER_BLOB,
        TO_TIMESTAMP(UPDATE_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
        TO_TIMESTAMP(DOWNLOAD_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
        TO_TIMESTAMP(IMPORT_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
        SOURCESYSTEM_CD,
        UPLOAD_ID
FROM    TM_LZ.MODIFIER_DIMENSION_I2B2_MTM;
----------------------------------------------------



----------------------------------------------------
--CONCEPT_DIMENSION
----------------------------------------------------
SELECT * FROM TM_LZ.CONCEPT_DIMENSION_I2B2_MTM WHERE CONCEPT_PATH LIKE '\i2b2\Allergy\Food Allergy\%';
SELECT * FROM I2B2DEMODATA.CONCEPT_DIMENSION;
DELETE FROM I2B2DEMODATA.CONCEPT_DIMENSION WHERE SOURCESYSTEM_CD LIKE 'i2b2::%';

INSERT INTO CONCEPT_DIMENSION 
(CONCEPT_CD, CONCEPT_PATH, NAME_CHAR, CONCEPT_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID, TABLE_NAME)
SELECT  CONCEPT_CD,
        REPLACE(CONCEPT_PATH,'\i2b2\','\BCH The Research Connection - Autism\i2b2\'),
        NAME_CHAR,
        CONCEPT_BLOB,
        TO_TIMESTAMP(UPDATE_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
        TO_TIMESTAMP(DOWNLOAD_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
        TO_TIMESTAMP(IMPORT_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
        'i2b2::' || SOURCESYSTEM_CD,
        UPLOAD_ID,
        'CONCEPT_DIMENSION'
FROM    TM_LZ.CONCEPT_DIMENSION_I2B2_MTM WHERE CONCEPT_PATH LIKE '\i2b2\Allergy\Food Allergy\%';

/*
DROP TABLE TM_LZ.CONCEPT_DIMENSION_I2B2_MTM_S;

--CREATE A TABLE FROM A SUBSET OF CONCEPTS.
CREATE TABLE TM_LZ.CONCEPT_DIMENSION_I2B2_MTM_S AS
(SELECT  *  
FROM    TM_LZ.CONCEPT_DIMENSION_I2B2_MTM CD
WHERE   CONCEPT_PATH LIKE '\i2b2\Allergy\Food Allergy\%');

SELECT * FROM TM_LZ.CONCEPT_DIMENSION_I2B2_MTM_S;

SELECT  CONCEPT_PATH,
        REPLACE(CONCEPT_PATH,'\i2b2\','\BCH The Research Connection - Autism\SFARI Simplex Collection v14\i2b2\')
FROM TM_LZ.CONCEPT_DIMENSION_I2B2_MTM_S;


--SELECT ONLY THE CONCEPTS WHERE WE'VE OBSERVED THEM IN PATIENTS.
CREATE TABLE TM_LZ.CONCEPT_DIMENSION_I2B2_MTM_S AS
(SELECT  *  
FROM    TM_LZ.CONCEPT_DIMENSION_I2B2_MTM CD
WHERE   CD.CONCEPT_CD IN (SELECT CONCEPT_CD FROM TM_LZ.OBSERVATION_FACT_I2B2_MTM));

SELECT * FROM TM_LZ.CONCEPT_DIMENSION_I2B2_MTM WHERE CONCEPT_CD NOT IN (SELECT CONCEPT_CD FROM TM_LZ.CONCEPT_DIMENSION_I2B2_MTM_S);
SELECT COUNT(1) FROM TM_LZ.CONCEPT_DIMENSION_I2B2_MTM_S;

SELECT * FROM TM_LZ.I2B2_I2B2_MTM WHERE C_VISUALATTRIBUTES LIKE 'FA%';
*/
----------------------------------------------------

----------------------------------------------------
--I2B2
----------------------------------------------------
SELECT * FROM TM_LZ.I2B2_I2B2_MTM;
SELECT * FROM I2B2METADATA.I2B2;
SELECT * FROM I2B2METADATA.I2B2 WHERE SOURCESYSTEM_CD = 'i2b2::Ag';
DELETE FROM I2B2METADATA.I2B2 WHERE SOURCESYSTEM_CD LIKE 'i2b2::%';

SELECT DISTINCT SOURCESYSTEM_CD FROM I2B2METADATA.I2B2;

INSERT INTO I2B2METADATA.I2B2
(C_HLEVEL, 
C_FULLNAME, 
C_NAME, 
C_SYNONYM_CD, 
C_VISUALATTRIBUTES, 
C_TOTALNUM, 
C_BASECODE, 
C_METADATAXML, 
C_FACTTABLECOLUMN, 
C_TABLENAME, 
C_COLUMNNAME, 
C_COLUMNDATATYPE, 
C_OPERATOR, 
C_DIMCODE, 
C_COMMENT, 
C_TOOLTIP, 
UPDATE_DATE, 
DOWNLOAD_DATE, 
IMPORT_DATE, 
SOURCESYSTEM_CD, 
VALUETYPE_CD, 
I2B2_ID, 
M_APPLIED_PATH, 
M_EXCLUSION_CD, 
C_PATH, 
C_SYMBOL);
  SELECT  C_HLEVEL+1, 
  REPLACE(C_FULLNAME,'\i2b2\','\BCH The Research Connection - Autism\i2b2\'), 
  C_NAME, 
  C_SYNONYM_CD, 
  C_VISUALATTRIBUTES, 
  C_TOTALNUM, 
  C_BASECODE, 
  C_METADATAXML, 
  C_FACTTABLECOLUMN, 
  C_TABLENAME, 
  C_COLUMNNAME, 
  C_COLUMNDATATYPE, 
  C_OPERATOR, 
  REPLACE(C_DIMCODE,'\i2b2\','\BCH The Research Connection - Autism\i2b2\'), 
  C_COMMENT, 
  C_TOOLTIP, 
  TO_TIMESTAMP(UPDATE_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
  TO_TIMESTAMP(DOWNLOAD_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
  TO_TIMESTAMP(IMPORT_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
  'i2b2::' || SOURCESYSTEM_CD, 
  VALUETYPE_CD, 
  I2B2_ID, 
  M_APPLIED_PATH, 
  M_EXCLUSION_CD, 
  C_PATH, 
  C_SYMBOL
  FROM    TM_LZ.I2B2_I2B2_MTM 
  WHERE C_FULLNAME LIKE '\i2b2\Allergy\Food Allergy\%';
  
  
  exec TM_CZ.I2B2_FILL_IN_TREE('AUTISM','\BCH The Research Connection - Autism\i2b2\');
----------------------------------------------------

----------------------------------------------------
--PATIENT_DIMENSION
----------------------------------------------------
SELECT * FROM TM_LZ.PATIENT_DIMENSION_I2B2_MTM;

CREATE TABLE TM_LZ.I2B2_TO_BCH_MRN
(
  "PATIENT_NUM" VARCHAR2(2000 BYTE) NULL,
  "MRN" VARCHAR2(2000 BYTE) NULL
);

CREATE TABLE TM_LZ.BCH_MRN_TO_FAMILY_ID
(
  "MRN" VARCHAR2(2000 BYTE) NULL,
  "PRIMARY_ID" VARCHAR2(2000 BYTE) NULL
);

--Dummy Data
INSERT INTO TM_LZ.I2B2_TO_BCH_MRN (PATIENT_NUM, MRN) VALUES ('102672','1');
INSERT INTO TM_LZ.BCH_MRN_TO_FAMILY_ID (MRN, PRIMARY_ID) VALUES ('1','1214.01');

INSERT INTO TM_LZ.I2B2_TO_BCH_MRN (PATIENT_NUM, MRN) VALUES ('1684224','2');
INSERT INTO TM_LZ.BCH_MRN_TO_FAMILY_ID (MRN, PRIMARY_ID) VALUES ('2','1216.01');

INSERT INTO TM_LZ.I2B2_TO_BCH_MRN (PATIENT_NUM, MRN) VALUES ('1638529','3');
INSERT INTO TM_LZ.BCH_MRN_TO_FAMILY_ID (MRN, PRIMARY_ID) VALUES ('3','1218.01');


SELECT * FROM TM_LZ.SSC_LINKAGE;
SELECT * FROM TM_LZ.OBSERVATION_FACT_I2B2_MTM;

SELECT * FROM I2B2DEMODATA.PATIENT_DIMENSION WHERE SOURCESYSTEM_CD LIKE 'AUTISM:11689%';
SELECT DISTINCT PATIENT_NUM FROM TM_LZ.OBSERVATION_FACT_I2B2_MTM WHERE CONCEPT_CD IN (SELECT CONCEPT_CD FROM TM_LZ.CONCEPT_DIMENSION_I2B2_MTM WHERE CONCEPT_PATH LIKE '\i2b2\Allergy\Food Allergy\%');
----------------------------------------------------



----------------------------------------------------
--OBSERVATION_FACT
----------------------------------------------------
SELECT * FROM TM_LZ.OBSERVATION_FACT_I2B2_MTM;
SELECT * FROM I2B2DEMODATA.OBSERVATION_FACT;

SELECT * FROM I2B2DEMODATA.PATIENT_DIMENSION WHERE SOURCESYSTEM_CD LIKE 'AUTISM:%';
SELECT * FROM I2B2DEMODATA.PATIENT_DIMENSION WHERE SOURCESYSTEM_CD LIKE 'AUTISM:1518%';

SELECT * FROM TM_LZ.PATIENT_DIMENSION_I2B2_MTM WHERE PATIENT_NUM = '1493868';
SELECT * FROM TM_LZ.SSC_LINKAGE WHERE PRIMARY_ID = '1518.01';
SELECT * FROM I2B2DEMODATA.PATIENT_DIMENSION WHERE SOURCESYSTEM_CD LIKE 'AUTISM:13796%';

SELECT * FROM TM_LZ.SSC_LINKAGE;

--CREATE A TABLE OF DISTINCT ENCOUNTER NUMBERS AND MAP THEM TO A NEW SEQUENCE ID.
CREATE TABLE TM_LZ.NEW_ENCOUNTER_NUM
(
  "ENCOUNTER_NUM" VARCHAR2(2000 BYTE) NULL,
  "NEW_ENCOUNTER_NUM" VARCHAR2(2000 BYTE) NULL
);

INSERT INTO TM_LZ.NEW_ENCOUNTER_NUM
SELECT t.ENCOUNTER_NUM,
        I2B2DEMODATA.SQ_UP_ENCDIM_ENCOUNTERNUM.nextval
FROM
(SELECT  DISTINCT ENCOUNTER_NUM
FROM    TM_LZ.OBSERVATION_FACT_I2B2_MTM OBSF ) t
;

--CREATE A NEW PARTITION FOR THIS OBSERVATION_FACT DATA BY SPLITTING THE DEFAULT PARTITION.
ALTER TABLE I2B2DEMODATA.OBSERVATION_FACT 
   SPLIT PARTITION OTHER_STUDIES VALUES ('AUTISM_I2B2') 
   INTO 
    ( PARTITION AUTISM_I2B2,
      PARTITION OTHER_STUDIES);


INSERT INTO I2B2DEMODATA.OBSERVATION_FACT
(ENCOUNTER_NUM, 
PATIENT_NUM, 
CONCEPT_CD, 
PROVIDER_ID, 
START_DATE, 
MODIFIER_CD, 
VALTYPE_CD, 
TVAL_CHAR, 
NVAL_NUM, 
VALUEFLAG_CD, 
QUANTITY_NUM, 
UNITS_CD, 
END_DATE, 
LOCATION_CD, 
CONFIDENCE_NUM, 
UPDATE_DATE, 
DOWNLOAD_DATE, 
IMPORT_DATE, 
SOURCESYSTEM_CD, 
UPLOAD_ID, 
OBSERVATION_BLOB, 
INSTANCE_NUM)
SELECT  NEN.NEW_ENCOUNTER_NUM, 
PD.PATIENT_NUM, 
OBSF.CONCEPT_CD, 
OBSF.PROVIDER_ID, 
OBSF.START_DATE, 
OBSF.MODIFIER_CD, 
OBSF.VALTYPE_CD, 
OBSF.TVAL_CHAR, 
OBSF.NVAL_NUM, 
OBSF.VALUEFLAG_CD, 
OBSF.QUANTITY_NUM, 
OBSF.UNITS_CD, 
OBSF.END_DATE, 
OBSF.LOCATION_CD, 
CONFIDENCE_NUM, 
TO_TIMESTAMP(OBSF.UPDATE_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
TO_TIMESTAMP(OBSF.DOWNLOAD_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
TO_TIMESTAMP(OBSF.IMPORT_DATE,'DD-MON-YY HH12.MI.SS.FF AM'),
'AUTISM_I2B2', 
OBSF.UPLOAD_ID, 
TO_LOB(OBSF.OBSERVATION_BLOB) OBSERVATION_BLOB, 
OBSF.INSTANCE_NUM
FROM TM_LZ.OBSERVATION_FACT_I2B2_MTM OBSF
INNER JOIN TM_LZ.NEW_ENCOUNTER_NUM NEN ON NEN.ENCOUNTER_NUM = OBSF.ENCOUNTER_NUM
INNER JOIN TM_LZ.I2B2_TO_BCH_MRN MAP1 ON MAP1.PATIENT_NUM = OBSF.PATIENT_NUM
INNER JOIN TM_LZ.BCH_MRN_TO_FAMILY_ID MAP2 ON MAP1.MRN = MAP2.MRN
INNER JOIN TM_LZ.SSC_LINKAGE LINK1 ON LINK1.PRIMARY_ID = MAP2.PRIMARY_ID
INNER JOIN I2B2DEMODATA.PATIENT_DIMENSION PD ON PD.SOURCESYSTEM_CD = 'AUTISM:' || LINK1.ID
WHERE CONCEPT_CD IN (SELECT CONCEPT_CD FROM TM_LZ.CONCEPT_DIMENSION_I2B2_MTM WHERE CONCEPT_PATH LIKE '\i2b2\Allergy\Food Allergy\%');
----------------------------------------------------



----------------------------------------------------
--VISIT_DIMENSION
----------------------------------------------------
SELECT * FROM TM_LZ.VISIT_DIMENSION_I2B2_MTM;
SELECT * FROM I2B2DEMODATA.OBSERVATION_FACT;



----------------------------------------------------






