/opt/data-integration/kitchen.sh \
-norep=Y \
-file=/opt/tranSMART-ETL/Kettle-GPL/Kettle-ETL-Michael/create_clinical_data.kjb \
-log=/opt/logs/load_clinical_data.log \
-level=Basic \
-param:COLUMN_MAP_FILE='PCORNETPRO_columns.txt' \
-param:DATA_LOCATION='/opt/data/' \
-param:STUDY_ID=PMS \
-param:TOP_NODE='\DBMI\PMS_DN\01 PMS Registry (Patient Reported Outcomes)\' \
-param:SORT_DIR='/opt/data/' \
-param:LOAD_TYPE=L \
-param:LOADER_PATH=/oracle01/app/oracle/product/11.2.0/client_1/bin/sqlldr \
-param:FACT_SET='HMS_PMS_REG_PRO'
