  CREATE TABLE "I2B2DEMODATA"."QT_PATIENT_SAMPLE_COLLECTION" 
   (	"RESULT_INSTANCE_ID" NUMBER(5,0), 
	"SAMPLE_ID" NUMBER(10,0), 
	"PATIENT_ID" NUMBER(10,0)
   ) TABLESPACE "I2B2_DATA" ;
   
CREATE SYNONYM QT_PATIENT_SAMPLE_COLLECTION FOR "I2B2DEMODATA"."QT_PATIENT_SAMPLE_COLLECTION";