--------------------------------------------------------
--  File created - Friday-January-03-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Index FACT_NOLOB
--------------------------------------------------------

  CREATE INDEX "I2B2DEMODATA"."FACT_NOLOB" ON "I2B2DEMODATA"."OBSERVATION_FACT" ("PATIENT_NUM", "START_DATE", "CONCEPT_CD", "ENCOUNTER_NUM", "INSTANCE_NUM", "NVAL_NUM", "TVAL_CHAR", "VALTYPE_CD", "MODIFIER_CD", "VALUEFLAG_CD", "PROVIDER_ID", "QUANTITY_NUM", "UNITS_CD", "END_DATE", "LOCATION_CD", "CONFIDENCE_NUM", "UPDATE_DATE", "DOWNLOAD_DATE", "IMPORT_DATE", "SOURCESYSTEM_CD", "UPLOAD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "I2B2_DATA" ;
