--------------------------------------------------------
--  DDL for Index IDX_CONCEPT_DIM3
--------------------------------------------------------

  CREATE INDEX "I2B2DEMODATA"."IDX_CONCEPT_DIM3" ON "I2B2DEMODATA"."CONCEPT_DIMENSION" ("CONCEPT_PATH", "CONCEPT_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "I2B2_DATA" ;