CREATE OR REPLACE PROCEDURE PATID_MAP_REGISTRY_TO_CLINOTES AS 
Original_Var NUMBER;
New_Var NUMBER;
BEGIN
for rec in (SELECT distinct PATIENT_NUM,  SOURCESYSTEM_CD FROM PATIENT_DIMENSION WHERE PATIENT_NUM LIKE '1%' AND SUBSTR(SOURCESYSTEM_CD,5) IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM LIKE '2%'))
LOOP
Original_Var := SUBSTR(rec.SOURCESYSTEM_CD,5);
New_Var := rec.PATIENT_NUM;

update observation_fact
set patient_num = New_Var
where sourcesystem_cd ='HMS_PMS_NLP_SNO' and concept_cd like 'SNO:%' and patient_num = Original_Var;

END LOOP;
commit;
  NULL;
END PATID_MAP_REGISTRY_TO_CLINOTES;